#!/usr/bin/env ruby

require 'shellwords'

url = Shellwords.escape(ARGV.pop)
exec ['curl', '-QsS', '-o', '-', '-L', url, "|", "tar", "-x", "--no-same-permissions", *ARGV.map{|a| Shellwords.escape(a)}].join(" ")
