#!/usr/bin/env bash

main=$(if git branch | grep '^[ *] main$' &> /dev/null; then echo "main"; else echo "master"; fi)
merged_branches=$(git branch --merged "$main" | grep -v "$main" | grep -v '^*')

for b in $merged_branches; do
	git branch -vd "$b"
done
