#!/usr/bin/env ruby
require 'shellwords'

localBranches = `git branch`.lines.map{|b| b[2..-1]}.map(&:chomp)
mainBranch = localBranches.include?('main') ? 'main' : 'master'

branches = `git branch --merged #{mainBranch} | grep -v #{mainBranch} | grep -vE '^\\*'`.lines.map(&:strip)

branches.each do |b|
  system 'git', 'branch', '-vd', b
end
