--
-- Built with,
--
--        ,gggg,
--       d8" "8I                         ,dPYb,
--       88  ,dP                         IP'`Yb
--    8888888P"                          I8  8I
--       88                              I8  8'
--       88        gg      gg    ,g,     I8 dPgg,
--  ,aa,_88        I8      8I   ,8'8,    I8dP" "8I
-- dP" "88P        I8,    ,8I  ,8'  Yb   I8P    I8
-- Yb,_,d88b,,_   ,d8b,  ,d8b,,8'_   8) ,d8     I8,
--  "Y8P"  "Y888888P'"Y88P"`Y8P' "YY8P8P88P     `Y8
--

-- vim: set nospell:
---@diagnostic disable: undefined-global

-- Based on a generated lush spec on Fri 21 Mar 2025 22:58:17 of the Andromeda theme from Sonokai
-- See https://github.com/sainnhe/sonokai/blob/master/colors/sonokai.vim

-- To simply check which highlight group is affecting something you can use :Inspect

local lush = require('lush')
local palette = require('usermod.theme.colors')

local theme = lush(function(injected_functions)
	local sym = injected_functions.sym

	return {
		-- Basic colours {{{
		Fg                 { fg=palette.fg, italic = false },
		Grey               { fg=palette.grey, italic = false },
		Red                { fg=palette.red, italic = false },
		RedSign            { fg=palette.red_sign },
		RedItalic          { fg=palette.red, italic = true },
		Green              { fg=palette.green, italic = false },
		GreenSign          { fg=palette.green_sign },
		GreenItalic        { fg=palette.green, italic = true },
		Yellow             { fg=palette.yellow, italic = false },
		YellowSign         { fg=palette.yellow_sign },
		YellowItalic       { fg=palette.yellow, italic = true },
		Orange             { fg=palette.orange, italic = false },
		OrangeSign         { fg=palette.orange_sign },
		OrangeItalic       { fg=palette.orange, italic = true },
		Blue               { fg=palette.blue, italic = false },
		BlueSign           { fg=palette.blue_sign },
		BlueItalic         { fg=palette.blue, italic = true },
		Purple             { fg=palette.purple, italic = false },
		PurpleSign         { fg=palette.purple_sign },
		PurpleItalic       { fg=palette.purple, italic = true },
		Cyan               { fg=palette.cyan, italic = false },
		CyanSign           { fg=palette.cyan },
		CyanItalic         { fg=palette.cyan, italic = true },
		Added              { Green },
		Removed            { Red },
		Changed            { Cyan },
		ErrorText          { gui='undercurl', sp=palette.red },
		WarningText        { gui='undercurl', sp=palette.yellow },
		InfoText           { gui='undercurl', sp=palette.blue },
		HintText           { gui='undercurl', sp=palette.green },
		SpellBad           { gui='undercurl', sp=palette.cyan },
		SpellCap           { gui='undercurl', sp=palette.cyan },
		SpellLocal         { gui='undercurl', sp=palette.cyan },
		SpellRare          { gui='undercurl', sp=palette.purple },
		ErrorLine          {},
		WarningLine        {},
		InfoLine           {},
		HintLine           {},
		VirtualTextError   { Red, bg=palette.bg_dim },
		VirtualTextWarning { Yellow, bg=palette.bg_dim },
		VirtualTextInfo    { Blue, bg=palette.bg_dim },
		VirtualTextHint    { Green, bg=palette.bg_dim },
		ErrorFloat         { Red, bg=palette.bg_dim },
		WarningFloat       { Yellow, bg=palette.bg_dim },
		InfoFloat          { Blue, bg=palette.bg_dim },
		HintFloat          { Green, bg=palette.bg_dim },
		CurrentWord        {},
		-- }}}

		-- Basic UI {{{
		Normal                               { fg=palette.fg, bg=palette.bg0 },
		NormalNC                             { fg=palette.fg, bg=palette.bg0 },
		Terminal                             { fg=palette.fg, bg=palette.bg0 },
		EndOfBuffer                          { fg=palette.bg4 },
		Folded                               { fg=palette.grey, bg=palette.bg1 },
		ToolbarLine                          { fg=palette.fg, bg=palette.bg2 },
		FoldColumn                           { fg=palette.grey_dim },
		SignColumn                           { fg=palette.fg },
		IncSearch                            { fg=palette.bg0, bg=palette.yellow },
		Search                               { fg=palette.bg0, bg=palette.bg_green },
		CurSearch                            { IncSearch },
		ColorColumn                          { bg=palette.bg2 },
		Conceal                              { fg=palette.grey_dim },
		Cursor                               { gui="reverse" },
		vCursor                              { Cursor },
		iCursor                              { Cursor },
		lCursor                              { Cursor },
		CursorIM                             { Cursor },
		CursorLine                           { bg=palette.bg1 },
		CursorColumn                         { bg=palette.bg1 },
		LineNr                               { fg=palette.grey_dim },
		CursorLineNr                         { fg=palette.fg },
		InlayHints                           { LineNr },
		DiffAdd                              { bg=palette.diff_green },
		DiffChange                           { bg=palette.diff_blue },
		DiffDelete                           { bg=palette.diff_red },
		DiffText                             { fg=palette.bg0, bg=palette.cyan },
		Directory                            { fg=palette.blue },
		ErrorMsg                             { fg=palette.red, bold=true, underline=true },
		WarningMsg                           { fg=palette.yellow, bold=true },
		ModeMsg                              { fg=palette.fg, bold=true },
		MoreMsg                              { fg=palette.blue, bold=true },
		MatchParen                           { bg=palette.bg4 },
		NonText                              { fg=palette.bg4 },
		Whitespace                           { NonText },
		SpecialKey                           { fg=palette.purple },
		Pmenu                                { fg=palette.fg, bg=palette.bg2 },
		PmenuSbar                            { bg=palette.bg2 },
		PmenuSel                             { fg=palette.bg0, bg=palette.bg_blue, blend=0 },
		PmenuKind                            { fg=palette.green, bg=palette.bg2 },
		PmenuExtra                           { fg=palette.grey, bg=palette.bg2 },
		WildMenu                             { PmenuSel },
		PmenuThumb                           { bg=palette.grey },
		NormalFloat                          { fg=palette.fg, bg=palette.bg2 },
		FloatBorder                          { fg=palette.grey, bg=palette.bg2 },
		FloatTitle                           { fg=palette.red, bg=palette.bg2, gui="bold" },
		Question                             { fg=palette.yellow },
		StatusLine                           { fg=palette.fg, bg=palette.bg3 },
		StatusLineTerm                       { fg=palette.fg, bg=palette.bg3 },
		StatusLineNC                         { fg=palette.grey, bg=palette.bg1 },
		StatusLineTermNC                     { fg=palette.grey, bg=palette.bg1 },
		TabLine                              { fg=palette.fg, bg=palette.bg4 },
		TabLineFill                          { fg=palette.grey, bg=palette.bg1 },
		TabLineSel                           { fg=palette.bg0, bg=palette.bg_red },
		WinBar                               { fg=palette.fg, bg=palette.bg3, bold=true },
		WinBarNC                             { fg=palette.grey, bg=palette.bg1 },
		VertSplit                            { fg=palette.black },
		WinSeparator                         { VertSplit },
		Visual                               { bg=palette.bg4 },
		VisualNOS                            { bg=palette.bg4, gui="underline" },
		QuickFixLine                         { fg=palette.blue, gui="bold" },
		Debug                                { fg=palette.yellow },
		debugPC                              { fg=palette.bg0, bg=palette.green },
		debugBreakpoint                      { fg=palette.bg0, bg=palette.red },
		ToolbarButton                        { fg=palette.bg0, bg=palette.bg_blue },
		Substitute                           { fg=palette.bg0, bg=palette.yellow },
		DiagnosticError                      { Red, bg=palette.bg_dim },
		DiagnosticWarn                       { Yellow, bg=palette.bg_dim },
		DiagnosticInfo                       { Blue, bg=palette.bg_dim },
		DiagnosticHint                       { Green, bg=palette.bg_dim },
		DiagnosticUnnecessary                { Grey },
		DiagnosticUnderlineError             { gui="undercurl", sp=palette.red },
		DiagnosticUnderlineWarn              { gui="undercurl", sp=palette.yellow },
		DiagnosticUnderlineInfo              { gui="undercurl", sp=palette.blue },
		DiagnosticUnderlineHint              { gui="undercurl", sp=palette.green },
		DiagnosticFloatingError              { ErrorFloat },
		DiagnosticFloatingWarn               { WarningFloat },
		DiagnosticFloatingInfo               { InfoFloat },
		DiagnosticFloatingHint               { HintFloat },
		DiagnosticVirtualTextError           { VirtualTextError },
		DiagnosticVirtualTextWarn            { VirtualTextWarning },
		DiagnosticVirtualTextInfo            { VirtualTextInfo },
		DiagnosticVirtualTextHint            { VirtualTextHint },
		DiagnosticSignError                  { RedSign },
		DiagnosticSignWarn                   { YellowSign },
		DiagnosticSignInfo                   { BlueSign },
		DiagnosticSignHint                   { GreenSign },
		LspDiagnosticsFloatingError          { DiagnosticFloatingError },
		LspDiagnosticsFloatingWarn           { DiagnosticFloatingWarn },
		LspDiagnosticsFloatingInformation    { DiagnosticFloatingInfo },
		LspDiagnosticsFloatingHint           { DiagnosticFloatingHint },
		LspDiagnosticsDefaultError           { DiagnosticError },
		LspDiagnosticsDefaultWarning         { DiagnosticWarn },
		LspDiagnosticsDefaultInformation     { DiagnosticInfo },
		LspDiagnosticsDefaultHint            { DiagnosticHint },
		LspDiagnosticsVirtualTextError       { DiagnosticVirtualTextError },
		LspDiagnosticsVirtualTextWarning     { DiagnosticVirtualTextWarn },
		LspDiagnosticsVirtualTextInformation { DiagnosticVirtualTextInfo },
		LspDiagnosticsVirtualTextHint        { DiagnosticVirtualTextHint },
		LspDiagnosticsUnderlineError         { DiagnosticUnderlineError },
		LspDiagnosticsUnderlineWarning       { DiagnosticUnderlineWarn },
		LspDiagnosticsUnderlineInformation   { DiagnosticUnderlineInfo },
		LspDiagnosticsUnderlineHint          { DiagnosticUnderlineHint },
		LspDiagnosticsSignError              { DiagnosticSignError },
		LspDiagnosticsSignWarning            { DiagnosticSignWarn },
		LspDiagnosticsSignInformation        { DiagnosticSignInfo },
		LspDiagnosticsSignHint               { DiagnosticSignHint },
		LspReferenceText                     { CurrentWord },
		LspReferenceRead                     { CurrentWord },
		LspReferenceWrite                    { CurrentWord },
		LspInlayHint                         { InlayHints },
		LspCodeLens                          { VirtualTextInfo },
		LspCodeLensSeparator                 { VirtualTextHint },
		LspSignatureActiveParameter          { Search },
		TermCursor                           { gui="reverse" },
		healthError                          { Red },
		healthSuccess                        { Green },
		healthWarning                        { Yellow },
		-- }}}

		-- Syntax highlighting {{{
		-- Builtin highlighting {{{
		Type           { fg=palette.blue, italic=true },
		Structure      { fg=palette.blue, italic=true },
		StorageClass   { fg=palette.blue, italic=true },
		Identifier     { Fg },
		Constant       { OrangeItalic },
		PreProc        { Conceal },
		PreCondit      { Conceal },
		Keyword        { Grey },
		Include        { Orange },
		Define         { Keyword },
		Typedef        { Keyword },
		Conditional    { Keyword },
		Repeat         { Keyword },
		Statement      { Keyword },
		Exception      { Red },
		Error          { Exception },
		Macro          { Cyan },
		Label          { Cyan },
		Special        { Cyan },
		SpecialChar    { Cyan },
		Boolean        { Yellow },
		String         { Yellow },
		Character      { Yellow },
		Number         { Yellow },
		Float          { Yellow },
		Function       { Fg },
		Operator       { Fg },
		Title          { fg=palette.red, bold=true },
		Tag            { Orange },
		Delimiter      { Fg },
		Todo           { fg=palette.bg0, bg=palette.blue, bold=true },
		Comment        { fg=palette.purple },
		SpecialComment { fg=palette.purple, italic=true },
		Ignore         { fg=palette.grey },
		Underlined     { underline=true },
		-- }}}

		-- Treesitter {{{
		TSEmphasis                     { italic=true },
		TSStrong                       { bold=true },
		TSStrike                       { Grey, strikethrough=true },
		TSUnderline                    { underline=true },
		TSDanger                       { fg=palette.bg0, bg=palette.red, bold=true },
		TSWarning                      { fg=palette.bg0, bg=palette.yellow, bold=true },
		TSNote                         { fg=palette.bg0, bg=palette.green, bold=true },
		TSTodo                         { Todo },
		TSAnnotation                   { Structure },
		TSAttribute                    { TSAnnotation },
		TSNamespace                    { Structure },
		TSStorageClass                 { StorageClass },
		TSStorageClassLifetime         { TSStorageClass },
		TSType                         { Type },
		TSTypeBuiltin                  { TSType },
		TSTypeDefinition               { TSType },
		TSTypeQualifier                { TSType },
		TSKeyword                      { Keyword },
		TSDefine                       { Define },
		TSKeywordFunction              { TSKeyword },
		TSKeywordOperator              { TSKeyword },
		TSKeywordReturn                { TSKeyword },
		TSInclude                      { Include },
		TSRepeat                       { TSKeyword },
		TSLiteral                      { String },
		TSBoolean                      { Boolean },
		TSCharacter                    { Character },
		TSCharacterSpecial             { Character },
		TSFloat                        { Float },
		TSMath                         { Yellow },
		TSNumber                       { Yellow },
		TSString                       { String },
		TSStringEscape                 { String },
		TSStringRegex                  { String },
		TSStringSpecial                { String },
		TSOperator                     { Operator },
		TSPunctBracket                 { Conceal },
		TSPunctDelimiter               { Conceal },
		TSPunctSpecial                 { Conceal },
		TSComment                      { Comment },
		TSConditional                  { Conditional },
		TSConstBuiltin                 { Constant },
		TSConstMacro                   { Constant },
		TSConstant                     { Constant },
		TSDebug                        { Debug },
		TSEnvironment                  { Macro },
		TSEnvironmentName              { Type },
		TSError                        { Error },
		TSException                    { Exception },
		TSField                        { Fg },
		TSProperty                     { TSField },
		TSConstructor                  { TSType },
		TSFunction                     { Function },
		TSFuncBuiltin                  { TSFunction },
		TSFuncMacro                    { TSFunction },
		TSFunctionCall                 { Green },
		TSLabel                        { Red },
		TSMethod                       { TSFunction },
		TSMethodCall                   { TSFunctionCall },
		TSNone                         { Fg },
		TSParameter                    { Fg },
		TSParameterReference           { Fg },
		TSPreProc                      { PreProc },
		TSSymbol                       { Fg },
		TSTagAttribute                 { Green },
		TSTagDelimiter                 { Red },
		TSText                         { Green },
		TSTextReference                { Constant },
		TSTitle                        { Title },
		TSTag                          { Tag },
		TSURI                          { fg=palette.blue, underline=true },
		TSVariable                     { Identifier },
		TSVariableBuiltin              { TSVariable },
		TSModuleInfoBad                { Red },
		TSModuleInfoGood               { Green },

		sym"@annotation"               { TSAnnotation },
		sym"@attribute"                { TSAttribute },
		sym"@boolean"                  { TSBoolean },
		sym"@character"                { TSCharacter },
		sym"@character.special"        { TSCharacterSpecial },
		sym"@comment"                  { TSComment },
		sym"@comment.error"            { TSDanger },
		sym"@comment.warning"          { TSWarning },
		sym"@comment.note"             { TSNote },
		sym"@comment.todo"             { TSTodo },
		sym"@conceal"                  { Conceal },
		sym"@conditional"              { TSConditional },
		sym"@constant"                 { TSConstant },
		sym"@constant.builtin"         { TSConstBuiltin },
		sym"@constant.macro"           { TSConstMacro },
		sym"@constructor"              { TSConstructor },
		sym"@debug"                    { TSDebug },
		sym"@define"                   { TSDefine },
		sym"@diff.delta"               { Changed },
		sym"@diff.minus"               { Removed },
		sym"@diff.plus"                { Added },
		sym"@error"                    { TSError }, -- This has been removed from nvim-treesitter
		sym"@exception"                { TSException },
		sym"@field"                    { TSField },
		sym"@float"                    { TSFloat },
		sym"@function"                 { TSFunction },
		sym"@function.builtin"         { TSFuncBuiltin },
		sym"@function.call"            { TSFunctionCall },
		sym"@function.macro"           { TSFuncMacro },
		sym"@function.method"          { TSMethod },
		sym"@function.method.call"     { TSMethodCall },
		sym"@include"                  { TSInclude },
		sym"@keyword"                  { TSKeyword },
		sym"@keyword.conditional"      { TSConditional },
		sym"@keyword.debug"            { TSDebug },
		sym"@keyword.directive"        { TSPreProc },
		sym"@keyword.directive.define" { TSDefine },
		sym"@keyword.exception"        { TSException },
		sym"@keyword.function"         { TSKeywordFunction },
		sym"@keyword.import"           { TSInclude },
		sym"@keyword.operator"         { TSKeywordOperator },
		sym"@keyword.repeat"           { TSRepeat },
		sym"@keyword.return"           { TSKeywordReturn },
		sym"@keyword.storage"          { TSStorageClass },
		sym"@label"                    { TSLabel },
		sym"@markup.emphasis"          { TSEmphasis },
		sym"@markup.environment"       { TSEnvironment },
		sym"@markup.environment.name"  { TSEnvironmentName },
		sym"@markup.heading"           { TSTitle },
		sym"@markup.italic"            { TSEmphasis },
		sym"@markup.link"              { TSTextReference },
		sym"@markup.link.label"        { TSStringSpecial },
		sym"@markup.link.url"          { TSURI },
		sym"@markup.list"              { TSPunctSpecial },
		sym"@markup.list.checked"      { Green },
		sym"@markup.list.unchecked"    { Ignore },
		sym"@markup.math"              { TSMath },
		sym"@markup.note"              { TSNote },
		sym"@markup.quote"             { Grey },
		sym"@markup.raw"               { TSLiteral },
		sym"@markup.strike"            { TSStrike },
		sym"@markup.strikethrough"     { strikethrough = true, },
		sym"@markup.strong"            { bold = true },
		sym"@markup.underline"         { underline = true },
		sym"@math"                     { TSMath },
		sym"@method"                   { TSMethod },
		sym"@method.call"              { TSMethodCall },
		sym"@module"                   { TSNamespace },
		sym"@namespace"                { TSNamespace },
		sym"@none"                     { TSNone },
		sym"@number"                   { TSNumber },
		sym"@number.float"             { TSFloat },
		sym"@operator"                 { TSOperator },
		sym"@parameter"                { TSParameter },
		sym"@parameter.reference"      { TSParameterReference },
		sym"@preproc"                  { TSPreProc },
		sym"@property"                 { TSProperty },
		sym"@punctuation.bracket"      { TSPunctBracket },
		sym"@punctuation.delimiter"    { TSPunctDelimiter },
		sym"@punctuation.special"      { TSPunctSpecial },
		sym"@repeat"                   { TSRepeat },
		sym"@storageclass"             { TSStorageClass },
		sym"@storageclass.lifetime"    { TSStorageClassLifetime },
		sym"@strike"                   { TSStrike },
		sym"@string"                   { TSString },
		sym"@string.escape"            { TSStringEscape },
		sym"@string.regex"             { TSStringRegex },
		sym"@string.regexp"            { sym"@string.regex" },
		sym"@string.special"           { TSStringSpecial },
		sym"@string.special.symbol"    { TSSymbol },
		sym"@string.special.uri"       { TSURI },
		sym"@symbol"                   { TSSymbol },
		sym"@tag"                      { TSTag },
		sym"@tag.attribute"            { TSTagAttribute },
		sym"@tag.delimiter"            { TSTagDelimiter },
		sym"@text"                     { TSText },
		sym"@text.danger"              { TSDanger },
		sym"@text.diff.add"            { Added },
		sym"@text.diff.delete"         { Removed },
		sym"@text.emphasis"            { TSEmphasis },
		sym"@text.environment"         { TSEnvironment },
		sym"@text.environment.name"    { TSEnvironmentName },
		sym"@text.literal"             { TSLiteral },
		sym"@text.math"                { TSMath },
		sym"@text.note"                { TSNote },
		sym"@text.reference"           { TSTextReference },
		sym"@text.strike"              { TSStrike },
		sym"@text.strong"              { TSStrong },
		sym"@text.title"               { TSTitle },
		sym"@text.todo"                { TSTodo },
		sym"@text.todo.checked"        { Green },
		sym"@text.todo.unchecked"      { Ignore },
		sym"@text.underline"           { TSUnderline },
		sym"@text.uri"                 { TSURI },
		sym"@text.warning"             { TSWarning },
		sym"@todo"                     { TSTodo },
		sym"@type"                     { TSType },
		sym"@type.builtin"             { TSTypeBuiltin },
		sym"@type.definition"          { TSTypeDefinition },
		sym"@type.qualifier"           { TSTypeQualifier },
		sym"@uri"                      { TSURI },
		sym"@variable"                 { TSVariable },
		sym"@variable.builtin"         { TSVariableBuiltin },
		sym"@variable.member"          { TSField },
		sym"@variable.parameter"       { TSParameter },
		-- }}}

		-- LSP {{{
		-- This is blanked out as it tends to conflict with Treesitter
		sym"@lsp.type.class"         {},
		sym"@lsp.type.comment"       {},
		sym"@lsp.type.decorator"     {},
		sym"@lsp.type.enum"          {},
		sym"@lsp.type.enumMember"    {},
		sym"@lsp.type.event"        {},
		sym"@lsp.type.events"        {},
		sym"@lsp.type.function"      {},
		sym"@lsp.type.interface"     {},
		sym"@lsp.type.keyword"       {},
		sym"@lsp.type.macro"         {},
		sym"@lsp.type.method"        {},
		sym"@lsp.type.modifier"      {},
		sym"@lsp.type.namespace"     {},
		sym"@lsp.type.number"        {},
		sym"@lsp.type.operator"      {},
		sym"@lsp.type.parameter"     {},
		sym"@lsp.type.property"      {},
		sym"@lsp.type.regexp"        {},
		sym"@lsp.type.string"        {},
		sym"@lsp.type.struct"        {},
		sym"@lsp.type.type"          {},
		sym"@lsp.type.typeParameter" {},
		sym"@lsp.type.variable"      {},
		-- }}}

		-- gitcommit {{{
		gitcommitSummary     { Red },
		gitcommitUntracked   { Grey },
		gitcommitDiscarded   { Grey },
		gitcommitSelected    { Grey },
		gitcommitUnmerged    { Grey },
		gitcommitOnBranch    { Grey },
		gitcommitArrow       { Grey },
		gitcommitFile        { Green },
		-- }}}

		-- html {{{
		sym"@tag.html"                 { TSTag },
		-- }}}

		-- json {{{
		sym"@property.json" { Orange },
		sym"@keyword.json5" { Orange },
		-- }}}

		-- toml {{{
		sym"@property.toml" { Orange },
		-- }}}

		-- typescript {{{
		sym"@_jsx_element"             { sym"@tag.html" },
		sym"@tag.builtin.tsx"          { PurpleItalic },
		-- }}}

		-- yaml {{{
		sym"@property.yaml" { Orange },
		-- }}}
		-- }}}

		-- Plugins {{{
		-- Barbar plugin {{{
		BufferCurrent         { Fg },
		BufferCurrentADDED    { fg=palette.green_sign, bg=pallete.bg0, },
		BufferCurrentCHANGED  { fg=palette.cyan_sign, bg=pallete.bg0, },
		BufferCurrentDELETED  { fg=palette.red_sign, bg=pallete.bg0, },
		BufferCurrentERROR    { fg=palette.red_sign, bg=pallete.bg0, },
		BufferCurrentHINT     { fg=palette.green_sign, bg=pallete.bg0, },
		BufferCurrentINFO     { fg=palette.blue_sign, bg=pallete.bg0, },
		BufferCurrentWARN     { fg=palette.yellow_sign, bg=palette.bg0, },
		BufferCurrentIndex    { BufferCurrent },
		BufferCurrentSign     { fg=palette.black, bg=palette.bg0, },
		BufferCurrentMod      { fg=palette.yellow, bg=palette.bg0, },
		BufferCurrentTarget   { fg=palette.red, bg=palette.bg0, gui="bold", },
		BufferInactive        { fg=palette.grey, bg=palette.bg_dim, },
		BufferInactiveADDED   { fg=palette.green_sign, bg=palette.bg_dim, },
		BufferInactiveCHANGED { fg=palette.cyan_sign, bg=palette.bg_dim, },
		BufferInactiveDELETED { fg=palette.red_sign, bg=palette.bg_dim, },
		BufferInactiveERROR   { fg=palette.red_sign, bg=palette.bg_dim, },
		BufferInactiveHINT    { fg=palette.green_sign, bg=palette.bg_dim, },
		BufferInactiveINFO    { fg=palette.blue_sign, bg=palette.bg_dim, },
		BufferInactiveWARN    { fg=palette.yellow_sign, bg=palette.bg_dim, },
		BufferInactiveIndex   { BufferInactive },
		BufferInactiveMod     { fg=palette.yellow_sign, bg=palette.bg_dim },
		BufferInactiveSign    { fg=palette.black, bg=palette.bg_dim, },
		BufferInactiveTarget  { fg=palette.yellow, bg=palette.bg_dim, gui="bold", },
		BufferTabpagesSep     { fg=palette.fg, bg=palette.bg1, gui="bold", },
		BufferScrollArrow     { BufferTabpagesSep },
		BufferTabpageFill     { fg=palette.black, bg=palette.black, },
		BufferTabpages        { fg=palette.grey, bg=palette.bg_dim, gui="bold", },
		BufferVisible         { fg=palette.fg, bg=palette.bg_dim, },
		BufferVisibleADDED    { BufferInactiveADDED },
		BufferVisibleCHANGED  { BufferInactiveCHANGED },
		BufferVisibleDELETED  { BufferInactiveDELETED },
		BufferVisibleERROR    { BufferInactiveERROR },
		BufferVisibleHINT     { BufferInactiveHINT },
		BufferVisibleINFO     { BufferInactiveINFO },
		BufferVisibleWARN     { BufferInactiveWARN },
		BufferVisibleIndex    { BufferVisible },
		BufferVisibleMod      { fg=palette.blue, bg=palette.bg_dim, },
		BufferVisibleSign     { fg=palette.black, bg=palette.bg_dim, },
		BufferVisibleTarget   { fg=palette.yellow, bg=palette.bg_dim, gui="bold", },
		-- }}}

		-- nvim-tree plugin {{{
		NvimTreeNormal                                                             { Normal },
		NvimTreeEndOfBuffer                                                        { EndOfBuffer },
		NvimTreeVertSplit                                                          { VertSplit },
		NvimTreeCursorColumn                                                       { CursorColumn },
		NvimTreeCursorLine                                                         { CursorLine },

		NvimTreeSymlink                                                            { fg=palette.cyan, gui="underline" },
		NvimTreeRootFolder                                                         { Title },
		NvimTreeFolderName                                                         { Directory },
		NvimTreeFolderIcon                                                         { Yellow },
		NvimTreeEmptyFolderName                                                    { NvimTreeFolderName },
		NvimTreeOpenedFolderName                                                   { NvimTreeFolderName },
		NvimTreeSymlinkFolderName                                                  { NvimTreeSymlink },
		NvimTreeExecFile                                                           { Green },
		NvimTreeOpenedFile                                                         { Grey },
		NvimTreeOpenedHL                                                           { Grey },
		NvimTreeSpecialFile                                                        { Fg },
		NvimTreeImageFile                                                          { Fg },
		NvimTreeMarkdownFile                                                       { Fg },
		NvimTreeIndentMarker                                                       { Grey },
		NvimTreeGitDirtyIcon                                                       { Yellow },
		NvimTreeGitStagedIcon                                                      { Blue },
		NvimTreeGitMergeIcon                                                       { Orange },
		NvimTreeGitRenamedIcon                                                     { Purple },
		NvimTreeGitNewIcon                                                         { Green },
		NvimTreeGitDeletedIcon                                                     { Red },
		NvimTreeCutHL                                                              { gui="undercurl", sp=palette.red, },
		NvimTreeCopiedHL                                                           { gui="undercurl", sp=palette.blue, },
		NvimTreeBookmarkHL                                                         { gui="undercurl", sp=palette.green, },

		NvimTreeLiveFilterValue                                                    { ModeMsg },
		NvimTreeLineNr                                                             { LineNr },
		NvimTreeCursorLineNr                                                       { CursorLineNr },
		NvimTreeStatusLine                                                         { StatusLine },
		NvimTreeStatusLineNC                                                       { StatusLineNC },
		NvimTreeHiddenIcon                                                         { Conceal },
		NvimTreeHiddenDisplay                                                      { Conceal },
		NvimTreeNormalFloat                                                        { NormalFloat },
		NvimTreeNormalFloatBorder                                                  { FloatBorder },
		NvimTreePopup                                                              { Normal },
		NvimTreeLiveFilterPrefix                                                   { PreProc },
		NvimTreeModifiedIcon                                                       { Type },
		NvimTreeDiagnosticErrorIcon                                                { fg=palette.red, bg=palette.bg0 },
		NvimTreeDiagnosticWarnIcon                                                 { fg=palette.yellow, bg=palette.bg0 },
		NvimTreeDiagnosticInfoIcon                                                 { fg=palette.blue, bg=palette.bg0 },
		NvimTreeDiagnosticHintIcon                                                 { fg=palette.green, bg=palette.bg0 },
		NvimTreeDiagnosticErrorFileHL                                              { DiagnosticUnderlineError },
		NvimTreeDiagnosticWarnFileHL                                               { DiagnosticUnderlineWarn },
		NvimTreeDiagnosticInfoFileHL                                               { DiagnosticUnderlineInfo },
		NvimTreeDiagnosticHintFileHL                                               { DiagnosticUnderlineHint },
		NvimTreeGitIgnoredIcon                                                     { Comment },
		NvimTreeBookmarkIcon                                                       { NvimTreeFolderIcon },
		NvimTreeOpenedFolderIcon                                                   { NvimTreeFolderIcon },
		NvimTreeClosedFolderIcon                                                   { NvimTreeFolderIcon },
		NvimTreeWindowPicker                                                       { fg=palette.bg0, bg=palette.bg_blue, gui="bold", },
		-- }}}

		-- GitSigns plugin {{{
		GitSignsAddInline                                                          { TermCursor },
		GitSignsDeleteInline                                                       { TermCursor },
		GitSignsChangeInline                                                       { TermCursor },
		GitSignsAddLn                                                              { DiffAdd },
		GitSignsAddPreview                                                         { DiffAdd },
		GitSignsChangeLn                                                           { DiffChange },
		GitSignsDeleteLn                                                           { DiffDelete },
		GitSignsDeletePreview                                                      { DiffDelete },
		GitSignsDeleteVirtLn                                                       { DiffDelete },
		GitSignsDelete                                                             { RedSign },
		GitSignsChange                                                             { CyanSign },
		GitSignsAdd                                                                { GreenSign },
		GitSignsDeleteNr                                                           { Red },
		GitSignsAddNr                                                              { Green },
		GitSignsCurrentLineBlame                                                   { Grey },
		GitSignsChangeNr                                                           { Blue },
		GitSignsStagedAdd                                                          { fg="#4f6836", },
		GitSignsStagedChange                                                       { fg="#366574", },
		GitSignsStagedDelete                                                       { fg="#7d303f", },
		GitSignsStagedChangedelete                                                 { fg="#366574", },
		GitSignsStagedTopdelete                                                    { fg="#7d303f", },
		GitSignsStagedUntracked                                                    { fg="#4f6836", },
		GitSignsStagedAddNr                                                        { fg="#4f6836", },
		GitSignsStagedChangeNr                                                     { fg="#366574", },
		GitSignsStagedDeleteNr                                                     { fg="#7d303f", },
		GitSignsStagedChangedeleteNr                                               { fg="#366574", },
		GitSignsStagedTopdeleteNr                                                  { fg="#7d303f", },
		GitSignsStagedUntrackedNr                                                  { fg="#4f6836", },
		GitSignsStagedAddLn                                                        { bg=palette.diff_green, },
		GitSignsStagedChangeLn                                                     { bg=palette.diff_blue, },
		GitSignsStagedChangedeleteLn                                               { bg=palette.diff_blue, },
		GitSignsStagedTopdeleteLn                                                  { bg=palette.diff_red, },
		GitSignsStagedUntrackedLn                                                  { bg=palette.diff_green, },
		GitSignsStagedAddCul                                                       { fg="#4f6836", },
		GitSignsStagedChangeCul                                                    { fg="#366574", },
		GitSignsStagedDeleteCul                                                    { fg="#7d303f", },
		GitSignsStagedChangedeleteCul                                              { fg="#366574", },
		GitSignsStagedTopdeleteCul                                                 { fg="#7d303f", },
		GitSignsStagedUntrackedCul                                                 { fg="#4f6836", },
		--- }}}

		-- which-key plugin {{{
		WhichKeyNormal     { NormalFloat },
		WhichKey           { Red },
		WhichKeySeperator  { Green },
		WhichKeyGroup      { Orange },
		WhichKeyDesc       { Cyan },
		WhichKeyIconAzure  { Blue },
		WhichKeyIconBlue   { Blue },
		WhichKeyIconCyan   { Cyan },
		WhichKeyIconGreen  { Green },
		WhichKeyIconGrey   { Grey },
		WhichKeyIconOrange { Orange },
		WhichKeyIconPurple { Purple },
		WhichKeyIconRed    { Red },
		WhichKeyIconYellow { Yellow },
		-- }}}
		-- }}}

		-- Unsorted miscellanea from initial import {{{
		MiniFilesDirectory                                                         { Directory },
		MiniPickIconDirectory                                                      { Directory },
		NvimInvalidSpacing                                                         { ErrorMsg },
		MiniOperatorsExchangeFrom                                                  { IncSearch },
		MiniPickPreviewRegion                                                      { IncSearch },
		MiniSurround                                                               { IncSearch },
		LspSignatureActiveParameter                                                { Search },
		EasyMotionTarget                                                           { Search },
		Sneak                                                                      { Search },
		SneakLabel                                                                 { Search },
		CleverFDefaultLabel                                                        { Search },
		MiniJump                                                                   { Search },
		MsgSeparator                                                               { StatusLine },
		CocListMode                                                                { StatusLine },
		CocListPath                                                                { StatusLine },
		FzfLuaTitle                                                                { Title },
		SnacksPickerTitle                                                          { Title },
		MiniDepsTitle                                                              { Title },
		MiniMapSymbolLine                                                          { Title },
		MiniStarterSection                                                         { Title },
		SnippetTabstop                                                             { Visual },
		HighlightedyankRegion                                                      { Visual },
		Lf_hl_rgHighlight                                                          { Visual },
		Lf_hl_gtagsHighlight                                                       { Visual },
		multiple_cursors_visual                                                    { Visual },
		NvimSurroundHighlight                                                      { Visual },
		CursorLineFold                                                             { FoldColumn },
		GitGutterAddLine                                                           { DiffAdd },
		SignifyLineAdd                                                             { DiffAdd },
		CocSnippetVisual                                                           { DiffAdd },
		LspSigActiveParameter                                                      { DiffAdd },
		Lf_hl_selection                                                            { DiffAdd },
		BookmarkAnnotationLine                                                     { DiffAdd },
		TelescopeSelection                                                         { DiffAdd },
		MiniDepsTitleUpdate                                                        { DiffAdd },
		MiniDiffOverAdd                                                            { DiffAdd },
		GitGutterChangeLine                                                        { DiffChange },
		SignifyLineChange                                                          { DiffChange },
		GitGutterChangeDeleteLine                                                  { DiffChange },
		SignifyLineChangeDelete                                                    { DiffChange },
		BookmarkLine                                                               { DiffChange },
		MiniDepsTitleSame                                                          { DiffChange },
		MiniDiffOverContext                                                        { DiffChange },
		MiniPickMatchMarked                                                        { DiffChange },
		GitGutterDeleteLine                                                        { DiffDelete },
		SignifyLineDelete                                                          { DiffDelete },
		MiniDepsTitleError                                                         { DiffDelete },
		MiniDiffOverDelete                                                         { DiffDelete },
		SneakScope                                                                 { DiffText },
		MiniDiffOverChange                                                         { DiffText },
		CursorLineSign                                                             { SignColumn },
		BlinkCmpGhostText                                                          { Conceal },
		CocPumMenu                                                                 { Pmenu },
		Lf_hl_popup_inputText                                                      { Pmenu },
		Lf_hl_popup_window                                                         { Pmenu },
		Lf_hl_popup_cwd                                                            { Pmenu },
		ClapInput                                                                  { Pmenu },
		ClapDisplay                                                                { Pmenu },
		ClapPreview                                                                { Pmenu },
		PmenuKindSel                                                               { PmenuSel },
		PmenuExtraSel                                                              { PmenuSel },
		CocMenuSel                                                                 { PmenuSel },
		CocNotificationButton                                                      { PmenuSel },
		BufTabLineActive                                                           { TabLine },
		BufTabLineCurrent                                                          { TabLineSel },
		BufTabLineHidden                                                           { TabLineFill },
		BufTabLineFill                                                             { TabLineFill },
		MiniTablineFill                                                            { TabLineFill },
		SnacksPickerListCursorLine                                                 { CursorLine },
		MiniFilesCursorLine                                                        { CursorLine },
		MiniPickMatchCurrent                                                       { CursorLine },
		MiniPickPreviewLine                                                        { CursorLine },
		CocFloating                                                                { NormalFloat },
		MiniAnimateNormalFloat                                                     { NormalFloat },
		MiniClueDescSingle                                                         { NormalFloat },
		MiniFilesNormal                                                            { NormalFloat },
		MiniMapNormal                                                              { NormalFloat },
		MiniNotifyNormal                                                           { NormalFloat },
		MiniPickNormal                                                             { NormalFloat },
		MiniClueBorder                                                             { FloatBorder },
		MiniFilesBorder                                                            { FloatBorder },
		MiniNotifyBorder                                                           { FloatBorder },
		MiniPickBorder                                                             { FloatBorder },
		multiple_cursors_cursor                                                    { Cursor },
		FloatFooter                                                                { FloatTitle },
		MiniClueTitle                                                              { FloatTitle },
		MiniFilesTitle                                                             { FloatTitle },
		MiniNotifyTitle                                                            { FloatTitle },
		MiniPickBorderText                                                         { FloatTitle },
		RedrawDebugNormal                                                          { gui="reverse", },
		NvimSpacing                                                                { Normal },
		SnacksPicker                                                               { Normal },
		SnacksPickerInputCursorLine                                                { Normal },
		SnacksPickerKeymapRhs                                                      { Normal },
		MiniStarterItem                                                            { Normal },
		NvimNumber                                                                 { Number },
		NvimNumberPrefix                                                           { Type },
		NvimOptionSigil                                                            { Type },
		SnacksPickerGitStatus                                                      { Special },
		MiniMapSymbolCount                                                         { Special },
		NvimRegister                                                               { SpecialChar },
		NvimStringSpecial                                                          { SpecialChar },
		DiagnosticWarning                                                          { DiagnosticWarn },
		MiniDepsMsgBreaking                                                        { DiagnosticWarn },
		DiagnosticInformation                                                      { DiagnosticInfo },
		MiniDepsInfo                                                               { DiagnosticInfo },
		MiniDepsHint                                                               { DiagnosticHint },
		DiagnosticOk                                                               { fg="nvimlightgreen", },
		DiagnosticFloatingOk                                                       { DiagnosticOk },
		DiagnosticVirtualTextOk                                                    { DiagnosticOk },
		DiagnosticSignOk                                                           { DiagnosticOk },
		SnacksPickerDir                                                            { Comment },
		MiniDepsPlaceholder                                                        { Comment },
		MiniJump2dDim                                                              { Comment },
		MiniStarterInactive                                                        { Comment },
		NvimString                                                                 { String },
		NvimIdentifier                                                             { Identifier },
		NvimAssignment                                                             { Operator },
		NvimOperator                                                               { Operator },
		NvimParenthesis                                                            { Delimiter },
		NvimColon                                                                  { Delimiter },
		NvimComma                                                                  { Delimiter },
		NvimArrow                                                                  { Delimiter },
		MiniMapSymbolView                                                          { Delimiter },
		MiniDepsChangeAdded                                                        { Added },
		MiniDepsChangeRemoved                                                      { Removed },
		DiagnosticDeprecated                                                       { gui="strikethrough", sp="nvimlightred", },
		FloatShadow                                                                { bg="nvimdarkgrey4", blend=80, },
		FloatShadowThrough                                                         { bg="nvimdarkgrey4", blend=100, },
		RedrawDebugClear                                                           { bg="nvimdarkyellow", },
		RedrawDebugComposed                                                        { bg="nvimdarkgreen", },
		RedrawDebugRecompose                                                       { bg="nvimdarkred", },
		NvimInvalid                                                                { Error },
		DiagnosticUnderlineOk                                                      { gui="underline", sp="nvimlightgreen", },
		NvimInternalError                                                          { fg=palette.red, bg=palette.bg_red, },
		NvimFigureBrace                                                            { NvimInternalError },
		NvimSingleQuotedUnknownEscape                                              { NvimInternalError },
		NvimInvalidSingleQuotedUnknownEscape                                       { NvimInternalError },
		CocErrorFloat                                                              { ErrorFloat },
		CocWarningFloat                                                            { WarningFloat },
		CocInfoFloat                                                               { InfoFloat },
		CocHintFloat                                                               { HintFloat },
		GitGutterDelete                                                            { RedSign },
		SignifySignDelete                                                          { RedSign },
		CocErrorSign                                                               { RedSign },
		CocGitRemovedSign                                                          { RedSign },
		CocGitTopRemovedSign                                                       { RedSign },
		LspDiagSignErrorText                                                       { RedSign },
		YcmErrorSign                                                               { RedSign },
		ALEErrorSign                                                               { RedSign },
		NeomakeErrorSign                                                           { RedSign },
		SyntasticErrorSign                                                         { RedSign },
		MiniDiffSignDelete                                                         { RedSign },
		CocWarningSign                                                             { YellowSign },
		LspDiagSignWarningText                                                     { YellowSign },
		YcmWarningSign                                                             { YellowSign },
		ALEWarningSign                                                             { YellowSign },
		NeomakeWarningSign                                                         { YellowSign },
		SyntasticWarningSign                                                       { YellowSign },
		GitGutterChange                                                            { BlueSign },
		SignifySignChange                                                          { BlueSign },
		CocInfoSign                                                                { BlueSign },
		CocGitChangedSign                                                          { BlueSign },
		LspDiagSignInfoText                                                        { BlueSign },
		ALEInfoSign                                                                { BlueSign },
		NeomakeInfoSign                                                            { BlueSign },
		SignatureMarkText                                                          { BlueSign },
		BookmarkSign                                                               { BlueSign },
		MiniDiffSignChange                                                         { BlueSign },
		GitGutterAdd                                                               { GreenSign },
		SignifySignAdd                                                             { GreenSign },
		CocHintSign                                                                { GreenSign },
		CocGitAddedSign                                                            { GreenSign },
		LspDiagSignHintText                                                        { GreenSign },
		NeomakeMessageSign                                                         { GreenSign },
		BookmarkAnnotationSign                                                     { GreenSign },
		MiniDiffSignAdd                                                            { GreenSign },
		CocHighlightText                                                           { CurrentWord },
		lspReference                                                               { CurrentWord },
		CurrentWordTwins                                                           { CurrentWord },
		illuminatedWord                                                            { CurrentWord },
		IlluminatedWordText                                                        { CurrentWord },
		IlluminatedWordRead                                                        { CurrentWord },
		IlluminatedWordWrite                                                       { CurrentWord },
		CursorWord0                                                                { CurrentWord },
		CursorWord1                                                                { CurrentWord },
		MiniCursorword                                                             { CurrentWord },
		MiniCursorwordCurrent                                                      { CurrentWord },
		GitGutterDeleteLineNr                                                      { Red },
		CocSelectedText                                                            { Red },
		CtrlPNoEntries                                                             { Red },
		RainbowLevel0                                                              { Red },
		agitRemote                                                                 { Red },
		agitStatRemoved                                                            { Red },
		agitDiffRemove                                                             { Red },
		CmpItemKindKey                                                             { Red },
		CmpItemKindKeyword                                                         { Red },
		CmpItemKindNamespace                                                       { Red },
		CmpItemKindOperator                                                        { Red },
		CmpItemKindPackage                                                         { Red },
		BlinkCmpKindKey                                                            { Red },
		BlinkCmpKindKeyword                                                        { Red },
		BlinkCmpKindNamespace                                                      { Red },
		BlinkCmpKindOperator                                                       { Red },
		BlinkCmpKindPackage                                                        { Red },
		NavicIconsKey                                                              { Red },
		NavicIconsKeyword                                                          { Red },
		NavicIconsNamespace                                                        { Red },
		NavicIconsOperator                                                         { Red },
		NavicIconsPackage                                                          { Red },
		RainbowDelimiterRed                                                        { Red },
		NotifyERRORBorder                                                          { Red },
		NotifyERRORIcon                                                            { Red },
		NotifyERRORTitle                                                           { Red },
		DapUIWatchesEmpty                                                          { Red },
		DapUIWatchesError                                                          { Red },
		LspSagaDiagnosticError                                                     { Red },
		LspSagaRenamePromptPrefix                                                  { Red },
		GitGutterAddLineNr                                                         { Green },
		CocMarkdownCode                                                            { Green },
		CocNotificationProgress                                                    { Green },
		deniteSelectedLine                                                         { Green },
		RainbowLevel3                                                              { Green },
		RainbowLevel7                                                              { Green },
		agitDate                                                                   { Green },
		agitStatAdded                                                              { Green },
		agitDiffAdd                                                                { Green },
		CmpItemKindConstructor                                                     { Green },
		CmpItemKindField                                                           { Green },
		CmpItemKindFile                                                            { Green },
		CmpItemKindFunction                                                        { Green },
		CmpItemKindMethod                                                          { Green },
		BlinkCmpKindConstructor                                                    { Green },
		BlinkCmpKindField                                                          { Green },
		BlinkCmpKindFile                                                           { Green },
		BlinkCmpKindFunction                                                       { Green },
		BlinkCmpKindMethod                                                         { Green },
		NavicIconsConstructor                                                      { Green },
		NavicIconsField                                                            { Green },
		NavicIconsFile                                                             { Green },
		NavicIconsFunction                                                         { Green },
		NavicIconsMethod                                                           { Green },
		SnacksDashboardKey                                                         { Green },
		RainbowDelimiterGreen                                                      { Green },
		NotifyINFOBorder                                                           { Green },
		NotifyINFOIcon                                                             { Green },
		NotifyINFOTitle                                                            { Green },
		DapUIThread                                                                { Green },
		DapUIWatchesValue                                                          { Green },
		DapUIBreakpointsInfo                                                       { Green },
		LspSagaDiagnosticHint                                                      { Green },
		LspSagaCodeActionContent                                                   { Green },
		LspSagaHoverBorder                                                         { Green },
		LspSagaDocTruncateLine                                                     { Green },
		LspSagaSignatureHelpBorder                                                 { Green },
		LspSagaShTruncateLine                                                      { Green },
		RainbowLevel2                                                              { Yellow },
		RainbowLevel6                                                              { Yellow },
		agitAuthor                                                                 { Yellow },
		CmpItemKindArray                                                           { Yellow },
		CmpItemKindBoolean                                                         { Yellow },
		CmpItemKindColor                                                           { Yellow },
		CmpItemKindDefault                                                         { Yellow },
		CmpItemKindEvent                                                           { Yellow },
		CmpItemKindFolder                                                          { Yellow },
		CmpItemKindNull                                                            { Yellow },
		CmpItemKindNumber                                                          { Yellow },
		CmpItemKindObject                                                          { Yellow },
		CmpItemKindReference                                                       { Yellow },
		CmpItemKindSnippet                                                         { Yellow },
		CmpItemKindString                                                          { Yellow },
		BlinkCmpKindArray                                                          { Yellow },
		BlinkCmpKindBoolean                                                        { Yellow },
		BlinkCmpKindColor                                                          { Yellow },
		BlinkCmpKindDefault                                                        { Yellow },
		BlinkCmpKindEvent                                                          { Yellow },
		BlinkCmpKindFolder                                                         { Yellow },
		BlinkCmpKindNull                                                           { Yellow },
		BlinkCmpKindNumber                                                         { Yellow },
		BlinkCmpKindObject                                                         { Yellow },
		BlinkCmpKindReference                                                      { Yellow },
		BlinkCmpKindSnippet                                                        { Yellow },
		BlinkCmpKindString                                                         { Yellow },
		NavicIconsArray                                                            { Yellow },
		NavicIconsBoolean                                                          { Yellow },
		NavicIconsColor                                                            { Yellow },
		NavicIconsDefault                                                          { Yellow },
		NavicIconsEvent                                                            { Yellow },
		NavicIconsFolder                                                           { Yellow },
		NavicIconsNull                                                             { Yellow },
		NavicIconsNumber                                                           { Yellow },
		NavicIconsObject                                                           { Yellow },
		NavicIconsReference                                                        { Yellow },
		NavicIconsSnippet                                                          { Yellow },
		NavicIconsString                                                           { Yellow },
		FzfLuaTitleFlags                                                           { Yellow },
		SnacksDashboardDesc                                                        { Yellow },
		SnacksPickerToggle                                                         { Yellow },
		RainbowDelimiterYellow                                                     { Yellow },
		NotifyWARNBorder                                                           { Yellow },
		NotifyWARNIcon                                                             { Yellow },
		NotifyWARNTitle                                                            { Yellow },
		LspSagaDiagnosticWarn                                                      { Yellow },
		LspLinesDiagBorder                                                         { Yellow },
		LineDiagTuncateLine                                                        { Yellow },
		MiniStarterFooter                                                          { Yellow },
		MiniStarterItemPrefix                                                      { Yellow },
		diffOldFile                                                                { Yellow },
		CocListsLine                                                               { Fg },
		Lf_hl_cursorline                                                           { Fg },
		ClapFile                                                                   { Fg },
		CmpItemAbbr                                                                { Fg },
		CmpItemMenu                                                                { Fg },
		CmpItemKindText                                                            { Fg },
		BlinkCmpKindText                                                           { Fg },
		NavicText                                                                  { Fg },
		NavicIconsText                                                             { Fg },
		TroubleText                                                                { Fg },
		LspSagaFinderSelection                                                     { Fg },
		CopilotSuggestion                                                          { Grey },
		CocPumShortcut                                                             { Grey },
		CocPumVirtualText                                                          { Grey },
		CocDisabled                                                                { Grey },
		CocFloatDividingLine                                                       { Grey },
		CocCodeLens                                                                { Grey },
		CocFadeOut                                                                 { Grey },
		CocStrikeThrough                                                           { Grey },
		CocListsDesc                                                               { Grey },
		ClapBlinesLineNr                                                           { Grey },
		EasyMotionShade                                                            { Grey },
		Blamer                                                                     { Grey },
		agitTree                                                                   { Grey },
		FloatermBorder                                                             { Grey },
		CmpItemAbbrDeprecated                                                      { Grey },
		NavicSeparator                                                             { Grey },
		TroubleSource                                                              { Grey },
		TroubleCode                                                                { Grey },
		TelescopeBorder                                                            { Grey },
		FzfLuaBorder                                                               { Grey },
		SnacksDashboardDir                                                         { Grey },
		SnacksPickerBorder                                                         { Grey },
		SnacksPickerTotals                                                         { Grey },
		HopUnmatched                                                               { Grey },
		NotifyDEBUGBorder                                                          { Grey },
		NotifyDEBUGIcon                                                            { Grey },
		NotifyDEBUGTitle                                                           { Grey },
		ReferencesCount                                                            { Grey },
		DefinitionCount                                                            { Grey },
		TargetFileName                                                             { Grey },
		MiniIndentscopeSymbol                                                      { Grey },
		MiniStarterItemBullet                                                      { Grey },
		LightspeedGreyWash                                                         { Grey },
		diffLine                                                                   { Grey },
		RainbowLevel1                                                              { Orange },
		agitRef                                                                    { Orange },
		agitStatMessage                                                            { Orange },
		CmpItemKindConstant                                                        { Orange },
		CmpItemKindProperty                                                        { Orange },
		CmpItemKindVariable                                                        { Orange },
		BlinkCmpKindConstant                                                       { Orange },
		BlinkCmpKindProperty                                                       { Orange },
		BlinkCmpKindVariable                                                       { Orange },
		NavicIconsConstant                                                         { Orange },
		NavicIconsProperty                                                         { Orange },
		NavicIconsVariable                                                         { Orange },
		RainbowDelimiterOrange                                                     { Orange },
		LspSagaDiagnosticSource                                                    { Orange },
		LspSagaDiagnosticBorder                                                    { Orange },
		diffNewFile                                                                { Orange },
		GitGutterChangeLineNr                                                      { Blue },
		Lf_hl_popup_prompt                                                         { Blue },
		CtrlPPrtCursor                                                             { Blue },
		RainbowLevel4                                                              { Blue },
		RainbowLevel8                                                              { Blue },
		agitHead                                                                   { Blue },
		agitTag                                                                    { Blue },
		agitStatFile                                                               { Blue },
		agitDiffHeader                                                             { Blue },
		CmpItemKind                                                                { Blue },
		CmpItemKindClass                                                           { Blue },
		CmpItemKindEnum                                                            { Blue },
		CmpItemKindInterface                                                       { Blue },
		CmpItemKindModule                                                          { Blue },
		CmpItemKindStruct                                                          { Blue },
		CmpItemKindTypeParameter                                                   { Blue },
		BlinkCmpKindClass                                                          { Blue },
		BlinkCmpKindEnum                                                           { Blue },
		BlinkCmpKindInterface                                                      { Blue },
		BlinkCmpKindModule                                                         { Blue },
		BlinkCmpKindStruct                                                         { Blue },
		BlinkCmpKindTypeParameter                                                  { Blue },
		NavicIconsClass                                                            { Blue },
		NavicIconsEnum                                                             { Blue },
		NavicIconsInterface                                                        { Blue },
		NavicIconsModule                                                           { Blue },
		NavicIconsStruct                                                           { Blue },
		NavicIconsTypeParameter                                                    { Blue },
		TelescopePromptPrefix                                                      { Blue },
		SnacksDashboardFile                                                        { Blue },
		SnacksDashboardHeader                                                      { Blue },
		SnacksDashboardIcon                                                        { Blue },
		SnacksPickerSelected                                                       { Blue },
		SnacksPickerBufFlags                                                       { Blue },
		HopNextKey2                                                                { Blue },
		RainbowDelimiterCyan                                                       { Blue },
		RainbowDelimiterBlue                                                       { Blue },
		DapUIScope                                                                 { Blue },
		DapUIDecoration                                                            { Blue },
		DapUIStoppedThread                                                         { Blue },
		DapUILineNumber                                                            { Blue },
		DapUIFloatBorder                                                           { Blue },
		DapUIBreakpointsPath                                                       { Blue },
		LspSagaDiagnosticInfo                                                      { Blue },
		LspSagaRenameBorder                                                        { Blue },
		LspSagaCodeActionBorder                                                    { Blue },
		LspSagaCodeActionTruncateLine                                              { Blue },
		LspSagaAutoPreview                                                         { Blue },
		MiniStarterQuery                                                           { Blue },
		Lf_hl_popup_spin                                                           { Purple },
		GitGutterChangeDeleteLineNr                                                { Purple },
		RainbowLevel5                                                              { Purple },
		CmpItemKindEnumMember                                                      { Purple },
		CmpItemKindUnit                                                            { Purple },
		CmpItemKindValue                                                           { Purple },
		BlinkCmpKindEnumMember                                                     { Purple },
		BlinkCmpKindUnit                                                           { Purple },
		BlinkCmpKindValue                                                          { Purple },
		NavicIconsEnumMember                                                       { Purple },
		NavicIconsUnit                                                             { Purple },
		NavicIconsValue                                                            { Purple },
		RainbowDelimiterViolet                                                     { Purple },
		NotifyTRACEBorder                                                          { Purple },
		NotifyTRACEIcon                                                            { Purple },
		NotifyTRACETitle                                                           { Purple },
		DapUIType                                                                  { Purple },
		DapUISource                                                                { Purple },
		LspSagaDefPreviewBorder                                                    { Purple },
		DefinitionIcon                                                             { Purple },
		MiniStarterHeader                                                          { Purple },
		LightspeedMaskedChar                                                       { Purple },
		diffFile                                                                   { Purple },
		diffIndexLine                                                              { Purple },
		SnacksDashboardTitle                                                       { RedItalic },
		CocGitChangeRemovedSign                                                    { PurpleSign },
		GitGutterChangeDelete                                                      { PurpleSign },
		SignifySignChangeDelete                                                    { PurpleSign },
		SignatureMarkerText                                                        { PurpleSign },
		CocErrorHighlight                                                          { ErrorText },
		LspErrorHighlight                                                          { ErrorText },
		LspDiagInlineError                                                         { ErrorText },
		YcmErrorSection                                                            { ErrorText },
		ALEError                                                                   { ErrorText },
		NeomakeError                                                               { ErrorText },
		SyntasticError                                                             { ErrorText },
		CocWarningHighlight                                                        { WarningText },
		LspWarningHighlight                                                        { WarningText },
		LspDiagInlineWarning                                                       { WarningText },
		YcmWarningSection                                                          { WarningText },
		ALEWarning                                                                 { WarningText },
		NeomakeWarning                                                             { WarningText },
		SyntasticWarning                                                           { WarningText },
		CocInfoHighlight                                                           { InfoText },
		LspInformationHighlight                                                    { InfoText },
		LspDiagInlineInfo                                                          { InfoText },
		ALEInfo                                                                    { InfoText },
		NeomakeInfo                                                                { InfoText },
		CocHintHighlight                                                           { HintText },
		LspHintHighlight                                                           { HintText },
		LspDiagInlineHint                                                          { HintText },
		NeomakeMessage                                                             { HintText },
		CocHoverRange                                                              { gui="bold,underline", },
		CocSearch                                                                  { fg=palette.green, gui="bold", },
		CocPumSearch                                                               { fg=palette.green, gui="bold", },
		CocMarkdownHeader                                                          { fg=palette.blue, gui="bold", },
		CocMarkdownLink                                                            { fg=palette.green, gui="underline", },
		Lf_hl_match                                                                { fg=palette.green, gui="bold", },
		Lf_hl_match0                                                               { fg=palette.green, gui="bold", },
		Lf_hl_match1                                                               { fg=palette.blue, gui="bold", },
		Lf_hl_match2                                                               { fg=palette.red, gui="bold", },
		Lf_hl_match3                                                               { fg=palette.yellow, gui="bold", },
		Lf_hl_match4                                                               { fg=palette.purple, gui="bold", },
		Lf_hl_matchRefine                                                          { fg=palette.yellow, gui="bold", },
		Lf_hl_popup_normalMode                                                     { fg=palette.bg0, bg=palette.blue, gui="bold", },
		Lf_hl_popup_inputMode                                                      { fg=palette.bg0, bg=palette.green, gui="bold", },
		Lf_hl_popup_category                                                       { fg=palette.fg, bg=palette.bg4, },
		Lf_hl_popup_nameOnlyMode                                                   { fg=palette.fg, bg=palette.bg3, },
		Lf_hl_popup_fullPathMode                                                   { fg=palette.fg, bg=palette.bg3, },
		Lf_hl_popup_fuzzyMode                                                      { fg=palette.fg, bg=palette.bg3, },
		Lf_hl_popup_regexMode                                                      { fg=palette.fg, bg=palette.bg3, },
		Lf_hl_popup_lineInfo                                                       { fg=palette.bg0, bg=palette.blue, },
		Lf_hl_popup_total                                                          { fg=palette.bg0, bg=palette.red, },
		Lf_hl_popup_cursor                                                         { fg=palette.bg0, bg=palette.blue, },
		ClapSelected                                                               { fg=palette.red, gui="bold", },
		ClapCurrentSelection                                                       { bg=palette.bg0, gui="bold", },
		ClapSpinner                                                                { fg=palette.blue, bg=palette.bg2, gui="bold", },
		ClapBlines                                                                 { fg=palette.fg, },
		ClapProviderColon                                                          { ClapBlines },
		ClapProviderAbout                                                          { ClapBlines },
		ClapProviderId                                                             { fg=palette.fg, gui="bold", },
		ClapMatches1                                                               { fg=palette.red, gui="bold", },
		ClapMatches2                                                               { fg=palette.orange, gui="bold", },
		ClapMatches3                                                               { fg=palette.yellow, gui="bold", },
		ClapMatches4                                                               { fg=palette.blue, gui="bold", },
		ClapMatches5                                                               { fg=palette.purple, gui="bold", },
		ClapFuzzyMatches                                                           { fg=palette.green, gui="bold", },
		ClapFuzzyMatches1                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches2                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches3                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches4                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches5                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches6                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches7                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches8                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches9                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches10                                                         { ClapFuzzyMatches },
		ClapFuzzyMatches11                                                         { ClapFuzzyMatches },
		ClapFuzzyMatches12                                                         { ClapFuzzyMatches },
		ClapSearchText                                                             { ClapFuzzyMatches },
		ClapNoMatchesFound                                                         { fg=palette.red, gui="bold", },
		deniteMatchedChar                                                          { fg=palette.green, gui="bold", },
		deniteMatchedRange                                                         { fg=palette.green, gui="bold,underline", },
		deniteInput                                                                { fg=palette.green, bg=palette.bg1, gui="bold", },
		deniteStatusLineNumber                                                     { fg=palette.purple, bg=palette.bg1, },
		deniteStatusLinePath                                                       { fg=palette.fg, bg=palette.bg1, },
		CtrlPMatch                                                                 { fg=palette.green, gui="bold", },
		CtrlPPrtBase                                                               { fg=palette.grey, },
		CtrlPLinePre                                                               { fg=palette.grey, },
		CtrlPMode1                                                                 { fg=palette.blue, bg=palette.bg1, gui="bold", },
		CtrlPMode2                                                                 { fg=palette.bg1, bg=palette.blue, gui="bold", },
		CtrlPStats                                                                 { fg=palette.grey, bg=palette.bg1, gui="bold", },
		MatchParenCur                                                              { gui="bold", },
		MatchWord                                                                  { gui="underline", },
		MatchWordCur                                                               { gui="underline", },
		SneakLabelMask                                                             { fg=palette.bg_green, bg=palette.bg_green, },
		VMCursor                                                                   { fg=palette.blue, bg=palette.grey_dim, },
		QuickScopePrimary                                                          { fg=palette.green, gui="underline", },
		QuickScopeSecondary                                                        { fg=palette.blue, gui="underline", },
		CmpItemAbbrMatch                                                           { fg=palette.green, gui="bold", },
		CmpItemAbbrMatchFuzzy                                                      { fg=palette.green, gui="bold", },
		BlinkCmpLabelMatch                                                         { fg=palette.green, gui="bold", },
		TelescopeMatching                                                          { fg=palette.green, gui="bold", },
		SnacksPickerMatch                                                          { fg=palette.green, gui="bold", },
		HopNextKey                                                                 { fg=palette.red, gui="bold", },
		HopNextKey1                                                                { fg=palette.blue, gui="bold", },
		IblScope                                                                   { fg=palette.grey, gui="nocombine", },
		IndentBlanklineContextChar                                                 { IblScope },
		IblIndent                                                                  { fg=palette.bg4, gui="nocombine", },
		IndentBlanklineChar                                                        { IblIndent },
		NotifyBackground                                                           { bg=palette.bg0, },
		DapUIModifiedValue                                                         { fg=palette.blue, gui="bold", },
		DapUIBreakpointsCurrentLine                                                { fg=palette.blue, gui="bold", },
		LspFloatWinBorder                                                          { fg=palette.bg0, bg=palette.bg0, },
		LspSagaDiagnosticHeader                                                    { fg=palette.orange, gui="bold", },
		LspSagaCodeActionTitle                                                     { fg=palette.blue, gui="bold", },
		DefinitionPreviewTitle                                                     { fg=palette.purple, gui="bold", },
		InclineNormalNC                                                            { fg=palette.grey, bg=palette.bg2, },
		MiniAnimateCursor                                                          { gui="reverse,nocombine", },
		MiniFilesFile                                                              { fg=palette.fg, },
		MiniFilesTitleFocused                                                      { fg=palette.green, bg=palette.bg2, gui="bold", },
		MiniHipatternsFixme                                                        { fg=palette.bg0, bg=palette.red, gui="bold", },
		MiniHipatternsHack                                                         { fg=palette.bg0, bg=palette.yellow, gui="bold", },
		MiniHipatternsNote                                                         { fg=palette.bg0, bg=palette.blue, gui="bold", },
		MiniHipatternsTodo                                                         { fg=palette.bg0, bg=palette.green, gui="bold", },
		MiniIconsAzure                                                             { fg=palette.bg_blue, },
		MiniIconsBlue                                                              { fg=palette.blue, },
		MiniIconsCyan                                                              { fg=palette.blue, },
		MiniIconsGreen                                                             { fg=palette.green, },
		MiniIconsGrey                                                              { fg=palette.fg, },
		MiniIconsOrange                                                            { fg=palette.orange, },
		MiniIconsPurple                                                            { fg=palette.purple, },
		MiniIconsRed                                                               { fg=palette.red, },
		MiniIconsYellow                                                            { fg=palette.yellow, },
		MiniIndentscopePrefix                                                      { gui="nocombine", },
		MiniJump2dSpot                                                             { fg=palette.red, gui="bold,nocombine", },
		MiniJump2dSpotAhead                                                        { fg=palette.blue, gui="nocombine", },
		MiniJump2dSpotUnique                                                       { fg=palette.yellow, gui="bold,nocombine", },
		MiniPickPrompt                                                             { fg=palette.blue, bg=palette.bg2, },
		MiniStarterCurrent                                                         { gui="nocombine", },
		MiniStatuslineDevinfo                                                      { fg=palette.fg, bg=palette.bg3, },
		MiniStatuslineFileinfo                                                     { fg=palette.fg, bg=palette.bg3, },
		MiniStatuslineFilename                                                     { fg=palette.grey, bg=palette.bg1, },
		MiniStatuslineInactive                                                     { fg=palette.grey, bg=palette.bg1, },
		MiniStatuslineModeCommand                                                  { fg=palette.bg0, bg=palette.yellow, gui="bold", },
		MiniStatuslineModeInsert                                                   { fg=palette.bg0, bg=palette.bg_green, gui="bold", },
		MiniStatuslineModeNormal                                                   { fg=palette.bg0, bg=palette.bg_blue, gui="bold", },
		MiniStatuslineModeOther                                                    { fg=palette.bg0, bg=palette.purple, gui="bold", },
		MiniStatuslineModeReplace                                                  { fg=palette.bg0, bg=palette.orange, gui="bold", },
		MiniStatuslineModeVisual                                                   { fg=palette.bg0, bg=palette.bg_red, gui="bold", },
		MiniTablineCurrent                                                         { fg=palette.fg, bg=palette.bg4, },
		MiniTablineHidden                                                          { fg=palette.grey, bg=palette.bg2, },
		MiniTablineModifiedCurrent                                                 { fg=palette.blue, bg=palette.bg4, },
		MiniTablineModifiedHidden                                                  { fg=palette.grey, bg=palette.bg2, },
		MiniTablineModifiedVisible                                                 { fg=palette.blue, bg=palette.bg2, },
		MiniTablineTabpagesection                                                  { fg=palette.bg0, bg=palette.blue, gui="bold", },
		MiniTablineVisible                                                         { fg=palette.fg, bg=palette.bg2, },
		MiniTestEmphasis                                                           { gui="bold", },
		MiniTestFail                                                               { fg=palette.red, gui="bold", },
		MiniTestPass                                                               { fg=palette.green, gui="bold", },
		MiniTrailspace                                                             { bg=palette.red, },
		LightspeedLabel                                                            { fg=palette.red, gui="bold,underline", },
		LightspeedLabelDistant                                                     { fg=palette.blue, gui="bold,underline", },
		LightspeedShortcut                                                         { fg=palette.bg0, bg=palette.red, gui="bold", },
		LightspeedUnlabeledMatch                                                   { fg=palette.fg, gui="bold", },
		LightspeedPendingOpArea                                                    { fg=palette.bg0, bg=palette.green, },
		-- }}}
	}
end)

return theme
