--
-- Built with,
--
--        ,gggg,
--       d8" "8I                         ,dPYb,
--       88  ,dP                         IP'`Yb
--    8888888P"                          I8  8I
--       88                              I8  8'
--       88        gg      gg    ,g,     I8 dPgg,
--  ,aa,_88        I8      8I   ,8'8,    I8dP" "8I
-- dP" "88P        I8,    ,8I  ,8'  Yb   I8P    I8
-- Yb,_,d88b,,_   ,d8b,  ,d8b,,8'_   8) ,d8     I8,
--  "Y8P"  "Y888888P'"Y88P"`Y8P' "YY8P8P88P     `Y8
--

-- vim: set nospell:
---@diagnostic disable: undefined-global

-- Generated lush spec on Fri 21 Mar 2025 22:58:17 based on the Andromeda theme from Sonokai
-- See https://github.com/sainnhe/sonokai/blob/master/colors/sonokai.vim

local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
local palette = {
	black =       '#181a1c',
	bg_dim =      '#252630',
	bg0 =         '#2b2d3a',
	bg1 =         '#333648',
	bg2 =         '#363a4e',
	bg3 =         '#393e53',
	bg4 =         '#3f445b',
	fg =          '#e1e3e4',
	grey =        '#7e8294',
	grey_dim =    '#5a5e7a',

	red =         '#fb617e',
	red_sign =    '#fb617e',
	bg_red =      '#ff6188',
	diff_red =    '#55393d',
	orange =      '#f89860',
	orange_sign = '#f89860',
	yellow =      '#edc763',
	yellow_sign = '#edc763',
	diff_yellow = '#4e432f',
	green =       '#9ed06c',
	green_sign =  '#9ed06c',
	bg_green =    '#a9dc76',
	diff_green =  '#394634',
	blue =        '#6dcae8',
	blue_sign =   '#6dcae8',
	bg_blue =     '#77d5f0',
	diff_blue =   '#354157',
	purple =      '#bb97ee',
	purple_sign = '#bb97ee',
}

local theme = lush(function(injected_functions)
	local sym = injected_functions.sym
	return {
		-- Basic colours {{{
		Fg                 { fg=palette.fg, },
		Grey               { fg=palette.grey, },
		Red                { fg=palette.red, },
		RedSign            { fg=palette.red_sign, },
		RedItalic          { fg=palette.red, gui="italic" },
		Orange             { fg=palette.orange, },
		OrangeSign         { fg=palette.orange_sign, },
		OrangeItalic       { fg=palette.orange, gui="italic" },
		Yellow             { fg=palette.yellow, },
		YellowSign         { fg=palette.yellow_sign, },
		YellowItalic       { fg=palette.yellow, gui="italic" },
		Green              { fg=palette.green, },
		GreenSign          { fg=palette.green_sign, },
		GreenItalic        { fg=palette.green, gui="italic" },
		Blue               { fg=palette.blue, },
		BlueSign           { fg=palette.blue_sign, },
		BlueItalic         { fg=palette.blue, gui="italic" },
		Purple             { fg=palette.purple, },
		PurpleSign         { fg=palette.purple_sign, },
		PurpleItalic       { fg=palette.purple, gui="italic" },
		Added              { Green },
		Removed            { Red },
		Changed            { Blue },
		ErrorText          { gui="undercurl", sp=palette.red, },
		WarningText        { gui="undercurl", sp=palette.yellow, },
		InfoText           { gui="undercurl", sp=palette.blue, },
		HintText           { gui="undercurl", sp=palette.green, },
		SpellBad           { gui="undercurl", sp=palette.green, },
		SpellCap           { gui="undercurl", sp=palette.green, },
		SpellLocal         { gui="undercurl", sp=palette.green, },
		SpellRare          { gui="undercurl", sp=palette.purple, },
		ErrorLine          {},
		WarningLine        {},
		InfoLine           {},
		HintLine           {},
		VirtualTextError   { fg=palette.red, },
		VirtualTextWarning { fg=palette.yellow, },
		VirtualTextInfo    { fg=palette.blue, },
		VirtualTextHint    { fg=palette.green, },
		ErrorFloat         { fg=palette.red, },
		WarningFloat       { fg=palette.yellow, },
		InfoFloat          { fg=palette.blue, },
		HintFloat          { fg=palette.green, },
		CurrentWord        { bg=palette.bg2, },
		-- }}}

		-- Basic UI {{{
		Normal                               { fg=palette.fg, bg=palette.bg0, },
		NormalNC                             { fg=palette.fg, bg=palette.bg0, },
		Terminal                             { fg=palette.fg, bg=palette.bg0, },
		EndOfBuffer                          { fg=palette.bg4, },
		Folded                               { fg=palette.grey, bg=palette.bg1, },
		ToolbarLine                          { fg=palette.fg, bg=palette.bg2, },
		FoldColumn                           { fg=palette.grey_dim, },
		SignColumn                           { fg=palette.fg, },
		IncSearch                            { fg=palette.bg0, bg=palette.yellow, },
		Search                               { fg=palette.bg0, bg=palette.bg_green, },
		CurSearch                            { IncSearch },
		ColorColumn                          { bg=palette.bg2, },
		Conceal                              { fg=palette.grey_dim, },
		Cursor                               { gui="reverse", },
		vCursor                              { Cursor },
		iCursor                              { Cursor },
		lCursor                              { Cursor },
		CursorIM                             { Cursor },
		CursorLine                           { bg=palette.bg1, },
		CursorColumn                         { bg=palette.bg1, },
		LineNr                               { fg=palette.grey_dim, },
		CursorLineNr                         { fg=palette.fg, },
		InlayHints                           { LineNr },
		DiffAdd                              { bg=palette.diff_green },
		DiffChange                           { bg=palette.diff_blue, },
		DiffDelete                           { bg=palette.diff_red, },
		DiffText                             { fg=palette.bg0, bg=palette.blue, },
		Directory                            { fg=palette.green, },
		ErrorMsg                             { fg=palette.red, gui="bold,underline", },
		WarningMsg                           { fg=palette.yellow, gui="bold", },
		ModeMsg                              { fg=palette.fg, gui="bold", },
		MoreMsg                              { fg=palette.blue, gui="bold", },
		MatchParen                           { bg=palette.bg4, },
		NonText                              { fg=palette.bg4, },
		Whitespace                           { fg=palette.bg4, },
		SpecialKey                           { fg=palette.purple, },
		Pmenu                                { fg=palette.fg, bg=palette.bg2, },
		PmenuSbar                            { bg=palette.bg2, },
		PmenuSel                             { fg=palette.bg0, bg=palette.bg_blue, blend=0, },
		PmenuKind                            { fg=palette.green, bg=palette.bg2, },
		PmenuExtra                           { fg=palette.grey, bg=palette.bg2, },
		WildMenu                             { PmenuSel },
		PmenuThumb                           { bg=palette.grey, },
		NormalFloat                          { fg=palette.fg, bg=palette.bg2, },
		FloatBorder                          { fg=palette.grey, bg=palette.bg2, },
		FloatTitle                           { fg=palette.red, bg=palette.bg2, gui="bold", },
		Question                             { fg=palette.yellow, },
		StatusLine                           { fg=palette.fg, bg=palette.bg3, },
		StatusLineTerm                       { fg=palette.fg, bg=palette.bg3, },
		StatusLineNC                         { fg=palette.grey, bg=palette.bg1, },
		StatusLineTermNC                     { fg=palette.grey, bg=palette.bg1, },
		TabLine                              { fg=palette.fg, bg=palette.bg4, },
		TabLineFill                          { fg=palette.grey, bg=palette.bg1, },
		TabLineSel                           { fg=palette.bg0, bg=palette.bg_red, },
		WinBar                               { fg=palette.fg, bg=palette.bg3, gui="bold", },
		WinBarNC                             { fg=palette.grey, bg=palette.bg1, },
		VertSplit                            { fg=palette.black, },
		WinSeparator                         { VertSplit },
		Visual                               { bg=palette.bg4, },
		VisualNOS                            { bg=palette.bg4, gui="underline", },
		QuickFixLine                         { fg=palette.blue, gui="bold", },
		Debug                                { fg=palette.yellow, },
		debugPC                              { fg=palette.bg0, bg=palette.green, },
		debugBreakpoint                      { fg=palette.bg0, bg=palette.red, },
		ToolbarButton                        { fg=palette.bg0, bg=palette.bg_blue, },
		Substitute                           { fg=palette.bg0, bg=palette.yellow, },
		DiagnosticError                      { fg=palette.red, },
		DiagnosticWarn                       { fg=palette.yellow, },
		DiagnosticInfo                       { fg=palette.blue, },
		DiagnosticHint                       { fg=palette.green, },
		DiagnosticUnderlineError             { gui="undercurl", sp=palette.red, },
		DiagnosticUnderlineWarn              { gui="undercurl", sp=palette.yellow, },
		DiagnosticUnderlineInfo              { gui="undercurl", sp=palette.blue, },
		DiagnosticUnderlineHint              { gui="undercurl", sp=palette.green, },
		DiagnosticFloatingError              { ErrorFloat },
		DiagnosticFloatingWarn               { WarningFloat },
		DiagnosticFloatingInfo               { InfoFloat },
		DiagnosticFloatingHint               { HintFloat },
		DiagnosticVirtualTextError           { VirtualTextError },
		DiagnosticVirtualTextWarn            { VirtualTextWarning },
		DiagnosticVirtualTextInfo            { VirtualTextInfo },
		DiagnosticVirtualTextHint            { VirtualTextHint },
		DiagnosticSignError                  { RedSign },
		DiagnosticSignWarn                   { YellowSign },
		DiagnosticSignInfo                   { BlueSign },
		DiagnosticSignHint                   { GreenSign },
		LspDiagnosticsFloatingError          { DiagnosticFloatingError },
		LspDiagnosticsFloatingWarn           { DiagnosticFloatingWarn },
		LspDiagnosticsFloatingInformation    { DiagnosticFloatingInfo },
		LspDiagnosticsFloatingHint           { DiagnosticFloatingHint },
		LspDiagnosticsDefaultError           { DiagnosticError },
		LspDiagnosticsDefaultWarning         { DiagnosticWarn },
		LspDiagnosticsDefaultInformation     { DiagnosticInfo },
		LspDiagnosticsDefaultHint            { DiagnosticHint },
		LspDiagnosticsVirtualTextError       { DiagnosticVirtualTextError },
		LspDiagnosticsVirtualTextWarning     { DiagnosticVirtualTextWarn },
		LspDiagnosticsVirtualTextInformation { DiagnosticVirtualTextInfo },
		LspDiagnosticsVirtualTextHint        { DiagnosticVirtualTextHint },
		LspDiagnosticsUnderlineError         { DiagnosticUnderlineError },
		LspDiagnosticsUnderlineWarning       { DiagnosticUnderlineWarn },
		LspDiagnosticsUnderlineInformation   { DiagnosticUnderlineInfo },
		LspDiagnosticsUnderlineHint          { DiagnosticUnderlineHint },
		LspDiagnosticsSignError              { DiagnosticSignError },
		LspDiagnosticsSignWarning            { DiagnosticSignWarn },
		LspDiagnosticsSignInformation        { DiagnosticSignInfo },
		LspDiagnosticsSignHint               { DiagnosticSignHint },
		LspReferenceText                     { CurrentWord },
		LspReferenceRead                     { CurrentWord },
		LspReferenceWrite                    { CurrentWord },
		LspInlayHint                         { InlayHints },
		LspCodeLens                          { VirtualTextInfo },
		LspCodeLensSeparator                 { VirtualTextHint },
		LspSignatureActiveParameter          { Search },
		TermCursor                           { gui="reverse", },
		healthError                          { Red },
		healthSuccess                        { Green },
		healthWarning                        { Yellow },
		-- }}}

		-- Syntax highlighting {{{
		-- Builtin highlighting {{{
		Type           { fg=palette.blue, gui="italic", },
		Structure      { fg=palette.blue, gui="italic", },
		StorageClass   { fg=palette.blue, gui="italic", },
		Identifier     { fg=palette.orange, gui="italic", },
		Constant       { fg=palette.orange, gui="italic", },
		PreProc        { fg=palette.red, },
		PreCondit      { fg=palette.red, },
		Include        { fg=palette.red, },
		Keyword        { fg=palette.red, },
		Define         { fg=palette.red, },
		Typedef        { fg=palette.red, },
		Exception      { fg=palette.red, },
		Conditional    { fg=palette.red, },
		Repeat         { fg=palette.red, },
		Statement      { fg=palette.red, },
		Macro          { fg=palette.purple, },
		Error          { fg=palette.red, },
		Label          { fg=palette.purple, },
		Special        { fg=palette.purple, },
		SpecialChar    { fg=palette.purple, },
		Boolean        { fg=palette.purple, },
		String         { fg=palette.yellow, },
		Character      { fg=palette.yellow, },
		Number         { fg=palette.purple, },
		Float          { fg=palette.purple, },
		Function       { fg=palette.green, },
		Operator       { fg=palette.red, },
		Title          { fg=palette.red, gui="bold", },
		Tag            { fg=palette.orange, },
		Delimiter      { fg=palette.fg, },
		Todo           { fg=palette.bg0, bg=palette.blue, gui="bold", },
		Comment        { fg=palette.grey, },
		SpecialComment { fg=palette.grey, gui="italic", },
		Ignore         { fg=palette.grey, },
		Underlined     { gui="underline", },
		-- }}}

		-- Treesitter {{{
		TSStrong               { gui="bold", },
		TSEmphasis             { gui="italic", },
		TSUnderline            { gui="underline", },
		TSNote                 { fg=palette.bg0, bg=palette.green, gui="bold", },
		TSWarning              { fg=palette.bg0, bg=palette.yellow, gui="bold", },
		TSDanger               { fg=palette.bg0, bg=palette.red, gui="bold", },
		TSAnnotation           { BlueItalic },
		TSAttribute            { BlueItalic },
		TSBoolean              { Purple },
		TSCharacter            { Yellow },
		TSCharacterSpecial     { SpecialChar },
		TSComment              { Comment },
		TSConditional          { Red },
		TSConstBuiltin         { PurpleItalic },
		TSConstMacro           { PurpleItalic },
		TSConstant             { Fg },
		TSConstructor          { Green },
		TSDebug                { Debug },
		TSDefine               { Define },
		TSEnvironment          { Macro },
		TSEnvironmentName      { Type },
		TSError                { Error },
		TSException            { Red },
		TSField                { Orange },
		TSFloat                { Purple },
		TSFuncBuiltin          { Green },
		TSFuncMacro            { Green },
		TSFunction             { Green },
		TSFunctionCall         { Green },
		TSInclude              { Red },
		TSLabel                { Red },
		TSLiteral              { String },
		TSKeyword              { Red },
		TSKeywordFunction      { Red },
		TSKeywordOperator      { Red },
		TSKeywordReturn        { Red },
		TSMath                 { Yellow },
		TSMethod               { Green },
		TSMethodCall           { Green },
		TSNamespace            { BlueItalic },
		TSNone                 { Fg },
		TSNumber               { Purple },
		TSOperator             { Red },
		TSParameter            { Fg },
		TSParameterReference   { Fg },
		TSPreProc              { PreProc },
		TSProperty             { Orange },
		TSPunctBracket         { Grey },
		TSPunctDelimiter       { Grey },
		TSPunctSpecial         { Yellow },
		TSRepeat               { Red },
		TSStorageClass         { Red },
		TSStorageClassLifetime { Red },
		TSStrike               { Grey },
		TSString               { Yellow },
		TSStringEscape         { Green },
		TSStringRegex          { Green },
		TSStringSpecial        { SpecialChar },
		TSSymbol               { Fg },
		TSTag                  { BlueItalic },
		TSTagAttribute         { Green },
		TSTagDelimiter         { Red },
		TSText                 { Green },
		TSTextReference        { Constant },
		TSTitle                { Title },
		TSTodo                 { Todo },
		TSType                 { BlueItalic },
		TSTypeBuiltin          { BlueItalic },
		TSTypeDefinition       { BlueItalic },
		TSTypeQualifier        { Red },
		TSURI                  { fg=palette.blue, gui="underline", },
		TSVariable             { Fg },
		TSVariableBuiltin      { PurpleItalic },
		TSModuleInfoBad        { Red },
		TSModuleInfoGood       { Green },
		-- }}}

		-- gitcommit {{{
		sym"@text.gitcommit"  { TSNone },
		-- }}}

		-- help {{{
		helpNote           { fg=palette.purple, gui='bold' },
		helpHeadline       { fg=palette.red, gui='bold' },
		helpHeader         { fg=palette.orange, gui='bold' },
		helpURL            { fg=palette.green, gui='underline' },
		helpHyperTextEntry { fg=palette.blue, gui='bold' },
		helpHyperTextJump  { Blue },
		helpCommand        { Yellow },
		helpExample        { Green },
		helpSpecial        { Purple },
		helpSectionDelim   { Grey },
		-- }}}
		-- }}}

		-- Plugins {{{
		-- Barbar plugin {{{
		BufferCurrent         { Fg },
		BufferCurrentADDED    { fg=palette.green_sign, bg=pallete.bg0, },
		BufferCurrentCHANGED  { fg=palette.blue_sign, bg=pallete.bg0, },
		BufferCurrentDELETED  { fg=palette.red_sign, bg=pallete.bg0, },
		BufferCurrentERROR    { fg=palette.red_sign, bg=pallete.bg0, },
		BufferCurrentHINT     { fg=palette.green_sign, bg=pallete.bg0, },
		BufferCurrentINFO     { fg=palette.blue_sign, bg=pallete.bg0, },
		BufferCurrentWARN     { fg=palette.yellow_sign, bg=palette.bg0, },
		BufferCurrentIndex    { BufferCurrent },
		BufferCurrentSign     { fg=palette.black, bg=palette.bg0, },
		BufferCurrentMod      { fg=palette.blue, bg=palette.bg0, },
		BufferCurrentTarget   { fg=palette.red, bg=palette.bg0, gui="bold", },
		BufferInactive        { fg=palette.grey, bg=palette.bg_dim, },
		BufferInactiveADDED   { fg=palette.green_sign, bg=palette.bg_dim, },
		BufferInactiveCHANGED { fg=palette.blue_sign, bg=palette.bg_dim, },
		BufferInactiveDELETED { fg=palette.red_sign, bg=palette.bg_dim, },
		BufferInactiveERROR   { fg=palette.red_sign, bg=palette.bg_dim, },
		BufferInactiveHINT    { fg=palette.green_sign, bg=palette.bg_dim, },
		BufferInactiveINFO    { fg=palette.blue_sign, bg=palette.bg_dim, },
		BufferInactiveWARN    { fg=palette.yellow_sign, bg=palette.bg_dim, },
		BufferInactiveIndex   { BufferInactive },
		BufferInactiveMod     { BufferInactive },
		BufferInactiveSign    { fg=palette.black, bg=palette.bg_dim, },
		BufferInactiveTarget  { fg=palette.yellow, bg=palette.bg_dim, gui="bold", },
		BufferTabpagesSep     { fg=palette.fg, bg=palette.bg1, gui="bold", },
		BufferScrollArrow     { BufferTabpagesSep },
		BufferTabpageFill     { fg=palette.black, bg=palette.black, },
		BufferTabpages        { fg=palette.grey, bg=palette.bg_dim, gui="bold", },
		BufferVisible         { fg=palette.fg, bg=palette.bg_dim, },
		BufferVisibleADDED    { BufferInactiveADDED },
		BufferVisibleCHANGED  { BufferInactiveCHANGED },
		BufferVisibleDELETED  { BufferInactiveDELETED },
		BufferVisibleERROR    { BufferInactiveERROR },
		BufferVisibleHINT     { BufferInactiveHINT },
		BufferVisibleINFO     { BufferInactiveINFO },
		BufferVisibleWARN     { BufferInactiveWARN },
		BufferVisibleIndex    { BufferVisible },
		BufferVisibleMod      { fg=palette.blue, bg=palette.bg_dim, },
		BufferVisibleSign     { fg=palette.black, bg=palette.bg_dim, },
		BufferVisibleTarget   { fg=palette.yellow, bg=palette.bg_dim, gui="bold", },
		-- }}}

		-- nvim-tree plugin {{{
		NvimTreeNormal                                                             { Normal },
		NvimTreeEndOfBuffer                                                        { EndOfBuffer },
		NvimTreeVertSplit                                                          { VertSplit },
		NvimTreeCursorColumn                                                       { CursorColumn },
		NvimTreeCursorLine                                                         { CursorLine },

		NvimTreeSymlink                                                            { Fg },
		NvimTreeFolderName                                                         { Directory },
		NvimTreeRootFolder                                                         { Title },
		NvimTreeFolderIcon                                                         { Blue },
		NvimTreeEmptyFolderName                                                    { NvimTreeFolderName },
		NvimTreeOpenedFolderName                                                   { NvimTreeFolderName },
		NvimTreeExecFile                                                           { Fg },
		NvimTreeOpenedFile                                                         { Fg },
		NvimTreeSpecialFile                                                        { Fg },
		NvimTreeImageFile                                                          { Fg },
		NvimTreeMarkdownFile                                                       { Fg },
		NvimTreeIndentMarker                                                       { Grey },
		NvimTreeGitDirtyIcon                                                       { Yellow },
		NvimTreeGitStagedIcon                                                      { Blue },
		NvimTreeGitMergeIcon                                                       { Orange },
		NvimTreeGitRenamedIcon                                                     { Purple },
		NvimTreeGitNewIcon                                                         { Green },
		NvimTreeGitDeletedIcon                                                     { Red },
		NvimTreeCutHL                                                              { gui="undercurl", sp=palette.red, },
		NvimTreeCopiedHL                                                           { gui="undercurl", sp=palette.blue, },
		NvimTreeBookmarkHL                                                         { gui="undercurl", sp=palette.green, },

		NvimTreeSymlinkFolderName                                                  { NvimTreeFolderName },
		NvimTreeLiveFilterValue                                                    { ModeMsg },
		NvimTreeLineNr                                                             { LineNr },
		NvimTreeCursorLineNr                                                       { CursorLineNr },
		NvimTreeStatusLine                                                         { StatusLine },
		NvimTreeStatusLineNC                                                       { StatusLineNC },
		NvimTreeHiddenIcon                                                         { Conceal },
		NvimTreeHiddenDisplay                                                      { Conceal },
		NvimTreeNormalFloat                                                        { NormalFloat },
		NvimTreeNormalFloatBorder                                                  { FloatBorder },
		NvimTreePopup                                                              { Normal },
		NvimTreeLiveFilterPrefix                                                   { PreProc },
		NvimTreeModifiedIcon                                                       { Type },
		NvimTreeOpenedHL                                                           { Special },
		NvimTreeDiagnosticErrorIcon                                                { DiagnosticError },
		NvimTreeDiagnosticWarnIcon                                                 { DiagnosticWarn },
		NvimTreeDiagnosticInfoIcon                                                 { DiagnosticInfo },
		NvimTreeDiagnosticHintIcon                                                 { DiagnosticHint },
		NvimTreeDiagnosticErrorFileHL                                              { DiagnosticUnderlineError },
		NvimTreeDiagnosticWarnFileHL                                               { DiagnosticUnderlineWarn },
		NvimTreeDiagnosticInfoFileHL                                               { DiagnosticUnderlineInfo },
		NvimTreeDiagnosticHintFileHL                                               { DiagnosticUnderlineHint },
		NvimTreeGitIgnoredIcon                                                     { Comment },
		NvimTreeBookmarkIcon                                                       { NvimTreeFolderIcon },
		NvimTreeOpenedFolderIcon                                                   { NvimTreeFolderIcon },
		NvimTreeClosedFolderIcon                                                   { NvimTreeFolderIcon },
		NvimTreeWindowPicker                                                       { fg=palette.bg0, bg=palette.bg_blue, gui="bold", },
		-- }}}

		-- Formatting options {{{
		sym"@markup.strong"        { TSStrong },
		sym"@text.strong"          { TSStrong },
		sym"@markup.italic"        { TSEmphasis },
		sym"@markup.emphasis"      { TSEmphasis },
		sym"@text.emphasis"        { TSEmphasis },
		sym"@markup.underline"     { TSUnderline },
		sym"@text.underline"       { TSUnderline },
		sym"@markup.strikethrough" { gui="strikethrough", },
		sym"@markup.link.url"      { TSURI },
		sym"@string.special.uri"   { TSURI },
		sym"@string.special.url"   { TSURI },
		sym"@text.uri"             { TSURI },
		sym"@uri"                  { TSURI },
		-- }}}

		-- GitSigns plugin {{{
		GitSignsAddInline                                                          { TermCursor },
		GitSignsDeleteInline                                                       { TermCursor },
		GitSignsChangeInline                                                       { TermCursor },
		GitSignsAddLn                                                              { DiffAdd },
		GitSignsAddPreview                                                         { DiffAdd },
		GitSignsChangeLn                                                           { DiffChange },
		GitSignsDeleteLn                                                           { DiffDelete },
		GitSignsDeletePreview                                                      { DiffDelete },
		GitSignsDeleteVirtLn                                                       { DiffDelete },
		GitSignsDelete                                                             { RedSign },
		GitSignsChange                                                             { BlueSign },
		GitSignsAdd                                                                { GreenSign },
		GitSignsDeleteNr                                                           { Red },
		GitSignsAddNr                                                              { Green },
		GitSignsCurrentLineBlame                                                   { Grey },
		GitSignsChangeNr                                                           { Blue },
		GitSignsStagedAdd                                                          { fg="#4f6836", },
		GitSignsStagedChange                                                       { fg="#366574", },
		GitSignsStagedDelete                                                       { fg="#7d303f", },
		GitSignsStagedChangedelete                                                 { fg="#366574", },
		GitSignsStagedTopdelete                                                    { fg="#7d303f", },
		GitSignsStagedUntracked                                                    { fg="#4f6836", },
		GitSignsStagedAddNr                                                        { fg="#4f6836", },
		GitSignsStagedChangeNr                                                     { fg="#366574", },
		GitSignsStagedDeleteNr                                                     { fg="#7d303f", },
		GitSignsStagedChangedeleteNr                                               { fg="#366574", },
		GitSignsStagedTopdeleteNr                                                  { fg="#7d303f", },
		GitSignsStagedUntrackedNr                                                  { fg="#4f6836", },
		GitSignsStagedAddLn                                                        { bg=palette.diff_green, },
		GitSignsStagedChangeLn                                                     { bg=palette.diff_blue, },
		GitSignsStagedChangedeleteLn                                               { bg=palette.diff_blue, },
		GitSignsStagedTopdeleteLn                                                  { bg=palette.diff_red, },
		GitSignsStagedUntrackedLn                                                  { bg=palette.diff_green, },
		GitSignsStagedAddCul                                                       { fg="#4f6836", },
		GitSignsStagedChangeCul                                                    { fg="#366574", },
		GitSignsStagedDeleteCul                                                    { fg="#7d303f", },
		GitSignsStagedChangedeleteCul                                              { fg="#366574", },
		GitSignsStagedTopdeleteCul                                                 { fg="#7d303f", },
		GitSignsStagedUntrackedCul                                                 { fg="#4f6836", },
		--- }}}
		-- }}}

		-- Unsorted miscellanea from initial import {{{
		MiniFilesDirectory                                                         { Directory },
		MiniPickIconDirectory                                                      { Directory },
		NvimInvalidSpacing                                                         { ErrorMsg },
		MiniOperatorsExchangeFrom                                                  { IncSearch },
		MiniPickPreviewRegion                                                      { IncSearch },
		MiniSurround                                                               { IncSearch },
		LspSignatureActiveParameter                                                { Search },
		EasyMotionTarget                                                           { Search },
		Sneak                                                                      { Search },
		SneakLabel                                                                 { Search },
		CleverFDefaultLabel                                                        { Search },
		MiniJump                                                                   { Search },
		MsgSeparator                                                               { StatusLine },
		CocListMode                                                                { StatusLine },
		CocListPath                                                                { StatusLine },
		FzfLuaTitle                                                                { Title },
		SnacksPickerTitle                                                          { Title },
		MiniDepsTitle                                                              { Title },
		MiniMapSymbolLine                                                          { Title },
		MiniStarterSection                                                         { Title },
		SnippetTabstop                                                             { Visual },
		HighlightedyankRegion                                                      { Visual },
		Lf_hl_rgHighlight                                                          { Visual },
		Lf_hl_gtagsHighlight                                                       { Visual },
		multiple_cursors_visual                                                    { Visual },
		NvimSurroundHighlight                                                      { Visual },
		CursorLineFold                                                             { FoldColumn },
		GitGutterAddLine                                                           { DiffAdd },
		SignifyLineAdd                                                             { DiffAdd },
		CocSnippetVisual                                                           { DiffAdd },
		LspSigActiveParameter                                                      { DiffAdd },
		Lf_hl_selection                                                            { DiffAdd },
		BookmarkAnnotationLine                                                     { DiffAdd },
		TelescopeSelection                                                         { DiffAdd },
		MiniDepsTitleUpdate                                                        { DiffAdd },
		MiniDiffOverAdd                                                            { DiffAdd },
		GitGutterChangeLine                                                        { DiffChange },
		SignifyLineChange                                                          { DiffChange },
		GitGutterChangeDeleteLine                                                  { DiffChange },
		SignifyLineChangeDelete                                                    { DiffChange },
		BookmarkLine                                                               { DiffChange },
		MiniDepsTitleSame                                                          { DiffChange },
		MiniDiffOverContext                                                        { DiffChange },
		MiniPickMatchMarked                                                        { DiffChange },
		GitGutterDeleteLine                                                        { DiffDelete },
		SignifyLineDelete                                                          { DiffDelete },
		MiniDepsTitleError                                                         { DiffDelete },
		MiniDiffOverDelete                                                         { DiffDelete },
		SneakScope                                                                 { DiffText },
		MiniDiffOverChange                                                         { DiffText },
		CursorLineSign                                                             { SignColumn },
		BlinkCmpGhostText                                                          { Conceal },
		CocPumMenu                                                                 { Pmenu },
		Lf_hl_popup_inputText                                                      { Pmenu },
		Lf_hl_popup_window                                                         { Pmenu },
		Lf_hl_popup_cwd                                                            { Pmenu },
		ClapInput                                                                  { Pmenu },
		ClapDisplay                                                                { Pmenu },
		ClapPreview                                                                { Pmenu },
		PmenuKindSel                                                               { PmenuSel },
		PmenuExtraSel                                                              { PmenuSel },
		CocMenuSel                                                                 { PmenuSel },
		CocNotificationButton                                                      { PmenuSel },
		BufTabLineActive                                                           { TabLine },
		BufTabLineCurrent                                                          { TabLineSel },
		BufTabLineHidden                                                           { TabLineFill },
		BufTabLineFill                                                             { TabLineFill },
		MiniTablineFill                                                            { TabLineFill },
		SnacksPickerListCursorLine                                                 { CursorLine },
		MiniFilesCursorLine                                                        { CursorLine },
		MiniPickMatchCurrent                                                       { CursorLine },
		MiniPickPreviewLine                                                        { CursorLine },
		CocFloating                                                                { NormalFloat },
		MiniAnimateNormalFloat                                                     { NormalFloat },
		MiniClueDescSingle                                                         { NormalFloat },
		MiniFilesNormal                                                            { NormalFloat },
		MiniMapNormal                                                              { NormalFloat },
		MiniNotifyNormal                                                           { NormalFloat },
		MiniPickNormal                                                             { NormalFloat },
		WhichKeyNormal                                                             { NormalFloat },
		MiniClueBorder                                                             { FloatBorder },
		MiniFilesBorder                                                            { FloatBorder },
		MiniNotifyBorder                                                           { FloatBorder },
		MiniPickBorder                                                             { FloatBorder },
		WhichKeyBorder                                                             { FloatBorder },
		multiple_cursors_cursor                                                    { Cursor },
		FloatFooter                                                                { FloatTitle },
		MiniClueTitle                                                              { FloatTitle },
		MiniFilesTitle                                                             { FloatTitle },
		MiniNotifyTitle                                                            { FloatTitle },
		MiniPickBorderText                                                         { FloatTitle },
		WhichKeyTitle                                                              { FloatTitle },
		RedrawDebugNormal                                                          { gui="reverse", },
		NvimSpacing                                                                { Normal },
		SnacksPicker                                                               { Normal },
		SnacksPickerInputCursorLine                                                { Normal },
		SnacksPickerKeymapRhs                                                      { Normal },
		MiniStarterItem                                                            { Normal },
		NvimNumber                                                                 { Number },
		NvimNumberPrefix                                                           { Type },
		NvimOptionSigil                                                            { Type },
		sym"@variable.parameter.builtin"                                           { Special },
		sym"@module.builtin"                                                       { Special },
		sym"@attribute.builtin"                                                    { Special },
		sym"@markup"                                                               { Special },
		sym"@tag.builtin"                                                          { Special },
		SnacksPickerGitStatus                                                      { Special },
		MiniMapSymbolCount                                                         { Special },
		NvimRegister                                                               { SpecialChar },
		NvimStringSpecial                                                          { SpecialChar },
		sym"@markup.list.unchecked"                                                { Ignore },
		sym"@text.todo.unchecked"                                                  { Ignore },
		DiagnosticWarning                                                          { DiagnosticWarn },
		MiniDepsMsgBreaking                                                        { DiagnosticWarn },
		DiagnosticInformation                                                      { DiagnosticInfo },
		MiniDepsInfo                                                               { DiagnosticInfo },
		MiniDepsHint                                                               { DiagnosticHint },
		DiagnosticOk                                                               { fg="nvimlightgreen", },
		DiagnosticFloatingOk                                                       { DiagnosticOk },
		DiagnosticVirtualTextOk                                                    { DiagnosticOk },
		DiagnosticSignOk                                                           { DiagnosticOk },
		DiagnosticUnnecessary                                                      { fg=palette.grey, },
		SnacksPickerDir                                                            { Comment },
		MiniDepsPlaceholder                                                        { Comment },
		MiniJump2dDim                                                              { Comment },
		MiniStarterInactive                                                        { Comment },
		WhichKeySeparator                                                          { Comment },
		WhichKeyValue                                                              { Comment },
		sym"@variable"                                                             { fg="nvimlightgrey2", },
		NvimString                                                                 { String },
		NvimIdentifier                                                             { Identifier },
		NvimAssignment                                                             { Operator },
		NvimOperator                                                               { Operator },
		sym"@punctuation"                                                          { Delimiter },
		NvimParenthesis                                                            { Delimiter },
		NvimColon                                                                  { Delimiter },
		NvimComma                                                                  { Delimiter },
		NvimArrow                                                                  { Delimiter },
		MiniMapSymbolView                                                          { Delimiter },
		diffAdded                                                                  { Added },
		MiniDepsChangeAdded                                                        { Added },
		diffRemoved                                                                { Removed },
		MiniDepsChangeRemoved                                                      { Removed },
		diffChanged                                                                { Changed },
		DiagnosticDeprecated                                                       { gui="strikethrough", sp="nvimlightred", },
		sym"@lsp.mod.deprecated"                                                   { DiagnosticDeprecated },
		FloatShadow                                                                { bg="nvimdarkgrey4", blend=80, },
		FloatShadowThrough                                                         { bg="nvimdarkgrey4", blend=100, },
		RedrawDebugClear                                                           { bg="nvimdarkyellow", },
		RedrawDebugComposed                                                        { bg="nvimdarkgreen", },
		RedrawDebugRecompose                                                       { bg="nvimdarkred", },
		NvimInvalid                                                                { Error },
		DiagnosticUnderlineOk                                                      { gui="underline", sp="nvimlightgreen", },
		NvimInternalError                                                          { fg=palette.red, bg=palette.bg_red, },
		NvimFigureBrace                                                            { NvimInternalError },
		NvimSingleQuotedUnknownEscape                                              { NvimInternalError },
		NvimInvalidSingleQuotedUnknownEscape                                       { NvimInternalError },
		CocErrorFloat                                                              { ErrorFloat },
		CocWarningFloat                                                            { WarningFloat },
		CocInfoFloat                                                               { InfoFloat },
		CocHintFloat                                                               { HintFloat },
		GitGutterDelete                                                            { RedSign },
		SignifySignDelete                                                          { RedSign },
		CocErrorSign                                                               { RedSign },
		CocGitRemovedSign                                                          { RedSign },
		CocGitTopRemovedSign                                                       { RedSign },
		LspDiagSignErrorText                                                       { RedSign },
		YcmErrorSign                                                               { RedSign },
		ALEErrorSign                                                               { RedSign },
		NeomakeErrorSign                                                           { RedSign },
		SyntasticErrorSign                                                         { RedSign },
		MiniDiffSignDelete                                                         { RedSign },
		CocWarningSign                                                             { YellowSign },
		LspDiagSignWarningText                                                     { YellowSign },
		YcmWarningSign                                                             { YellowSign },
		ALEWarningSign                                                             { YellowSign },
		NeomakeWarningSign                                                         { YellowSign },
		SyntasticWarningSign                                                       { YellowSign },
		GitGutterChange                                                            { BlueSign },
		SignifySignChange                                                          { BlueSign },
		CocInfoSign                                                                { BlueSign },
		CocGitChangedSign                                                          { BlueSign },
		LspDiagSignInfoText                                                        { BlueSign },
		ALEInfoSign                                                                { BlueSign },
		NeomakeInfoSign                                                            { BlueSign },
		SignatureMarkText                                                          { BlueSign },
		BookmarkSign                                                               { BlueSign },
		MiniDiffSignChange                                                         { BlueSign },
		GitGutterAdd                                                               { GreenSign },
		SignifySignAdd                                                             { GreenSign },
		CocHintSign                                                                { GreenSign },
		CocGitAddedSign                                                            { GreenSign },
		LspDiagSignHintText                                                        { GreenSign },
		NeomakeMessageSign                                                         { GreenSign },
		BookmarkAnnotationSign                                                     { GreenSign },
		MiniDiffSignAdd                                                            { GreenSign },
		CocHighlightText                                                           { CurrentWord },
		lspReference                                                               { CurrentWord },
		CurrentWordTwins                                                           { CurrentWord },
		illuminatedWord                                                            { CurrentWord },
		IlluminatedWordText                                                        { CurrentWord },
		IlluminatedWordRead                                                        { CurrentWord },
		IlluminatedWordWrite                                                       { CurrentWord },
		CursorWord0                                                                { CurrentWord },
		CursorWord1                                                                { CurrentWord },
		MiniCursorword                                                             { CurrentWord },
		MiniCursorwordCurrent                                                      { CurrentWord },
		GitGutterDeleteLineNr                                                      { Red },
		CocSelectedText                                                            { Red },
		CtrlPNoEntries                                                             { Red },
		RainbowLevel0                                                              { Red },
		WhichKey                                                                   { Red },
		agitRemote                                                                 { Red },
		agitStatRemoved                                                            { Red },
		agitDiffRemove                                                             { Red },
		CmpItemKindKey                                                             { Red },
		CmpItemKindKeyword                                                         { Red },
		CmpItemKindNamespace                                                       { Red },
		CmpItemKindOperator                                                        { Red },
		CmpItemKindPackage                                                         { Red },
		BlinkCmpKindKey                                                            { Red },
		BlinkCmpKindKeyword                                                        { Red },
		BlinkCmpKindNamespace                                                      { Red },
		BlinkCmpKindOperator                                                       { Red },
		BlinkCmpKindPackage                                                        { Red },
		NavicIconsKey                                                              { Red },
		NavicIconsKeyword                                                          { Red },
		NavicIconsNamespace                                                        { Red },
		NavicIconsOperator                                                         { Red },
		NavicIconsPackage                                                          { Red },
		RainbowDelimiterRed                                                        { Red },
		NotifyERRORBorder                                                          { Red },
		NotifyERRORIcon                                                            { Red },
		NotifyERRORTitle                                                           { Red },
		DapUIWatchesEmpty                                                          { Red },
		DapUIWatchesError                                                          { Red },
		LspSagaDiagnosticError                                                     { Red },
		LspSagaRenamePromptPrefix                                                  { Red },
		GitGutterAddLineNr                                                         { Green },
		sym"@markup.list.checked"                                                  { Green },
		sym"@text.todo.checked"                                                    { Green },
		CocMarkdownCode                                                            { Green },
		CocNotificationProgress                                                    { Green },
		deniteSelectedLine                                                         { Green },
		RainbowLevel3                                                              { Green },
		RainbowLevel7                                                              { Green },
		WhichKeySeperator                                                          { Green },
		agitDate                                                                   { Green },
		agitStatAdded                                                              { Green },
		agitDiffAdd                                                                { Green },
		CmpItemKindConstructor                                                     { Green },
		CmpItemKindField                                                           { Green },
		CmpItemKindFile                                                            { Green },
		CmpItemKindFunction                                                        { Green },
		CmpItemKindMethod                                                          { Green },
		BlinkCmpKindConstructor                                                    { Green },
		BlinkCmpKindField                                                          { Green },
		BlinkCmpKindFile                                                           { Green },
		BlinkCmpKindFunction                                                       { Green },
		BlinkCmpKindMethod                                                         { Green },
		NavicIconsConstructor                                                      { Green },
		NavicIconsField                                                            { Green },
		NavicIconsFile                                                             { Green },
		NavicIconsFunction                                                         { Green },
		NavicIconsMethod                                                           { Green },
		SnacksDashboardKey                                                         { Green },
		RainbowDelimiterGreen                                                      { Green },
		NotifyINFOBorder                                                           { Green },
		NotifyINFOIcon                                                             { Green },
		NotifyINFOTitle                                                            { Green },
		DapUIThread                                                                { Green },
		DapUIWatchesValue                                                          { Green },
		DapUIBreakpointsInfo                                                       { Green },
		LspSagaDiagnosticHint                                                      { Green },
		LspSagaCodeActionContent                                                   { Green },
		LspSagaHoverBorder                                                         { Green },
		LspSagaDocTruncateLine                                                     { Green },
		LspSagaSignatureHelpBorder                                                 { Green },
		LspSagaShTruncateLine                                                      { Green },
		RainbowLevel2                                                              { Yellow },
		RainbowLevel6                                                              { Yellow },
		agitAuthor                                                                 { Yellow },
		CmpItemKindArray                                                           { Yellow },
		CmpItemKindBoolean                                                         { Yellow },
		CmpItemKindColor                                                           { Yellow },
		CmpItemKindDefault                                                         { Yellow },
		CmpItemKindEvent                                                           { Yellow },
		CmpItemKindFolder                                                          { Yellow },
		CmpItemKindNull                                                            { Yellow },
		CmpItemKindNumber                                                          { Yellow },
		CmpItemKindObject                                                          { Yellow },
		CmpItemKindReference                                                       { Yellow },
		CmpItemKindSnippet                                                         { Yellow },
		CmpItemKindString                                                          { Yellow },
		BlinkCmpKindArray                                                          { Yellow },
		BlinkCmpKindBoolean                                                        { Yellow },
		BlinkCmpKindColor                                                          { Yellow },
		BlinkCmpKindDefault                                                        { Yellow },
		BlinkCmpKindEvent                                                          { Yellow },
		BlinkCmpKindFolder                                                         { Yellow },
		BlinkCmpKindNull                                                           { Yellow },
		BlinkCmpKindNumber                                                         { Yellow },
		BlinkCmpKindObject                                                         { Yellow },
		BlinkCmpKindReference                                                      { Yellow },
		BlinkCmpKindSnippet                                                        { Yellow },
		BlinkCmpKindString                                                         { Yellow },
		NavicIconsArray                                                            { Yellow },
		NavicIconsBoolean                                                          { Yellow },
		NavicIconsColor                                                            { Yellow },
		NavicIconsDefault                                                          { Yellow },
		NavicIconsEvent                                                            { Yellow },
		NavicIconsFolder                                                           { Yellow },
		NavicIconsNull                                                             { Yellow },
		NavicIconsNumber                                                           { Yellow },
		NavicIconsObject                                                           { Yellow },
		NavicIconsReference                                                        { Yellow },
		NavicIconsSnippet                                                          { Yellow },
		NavicIconsString                                                           { Yellow },
		FzfLuaTitleFlags                                                           { Yellow },
		SnacksDashboardDesc                                                        { Yellow },
		SnacksPickerToggle                                                         { Yellow },
		RainbowDelimiterYellow                                                     { Yellow },
		NotifyWARNBorder                                                           { Yellow },
		NotifyWARNIcon                                                             { Yellow },
		NotifyWARNTitle                                                            { Yellow },
		LspSagaDiagnosticWarn                                                      { Yellow },
		LspLinesDiagBorder                                                         { Yellow },
		LineDiagTuncateLine                                                        { Yellow },
		MiniStarterFooter                                                          { Yellow },
		MiniStarterItemPrefix                                                      { Yellow },
		diffOldFile                                                                { Yellow },
		CocListsLine                                                               { Fg },
		Lf_hl_cursorline                                                           { Fg },
		ClapFile                                                                   { Fg },
		CmpItemAbbr                                                                { Fg },
		CmpItemMenu                                                                { Fg },
		CmpItemKindText                                                            { Fg },
		BlinkCmpKindText                                                           { Fg },
		NavicText                                                                  { Fg },
		NavicIconsText                                                             { Fg },
		TroubleText                                                                { Fg },
		LspSagaFinderSelection                                                     { Fg },
		sym"@conceal"                                                              { Conceal },
		sym"@markup.quote"                                                         { Grey },
		CopilotSuggestion                                                          { Grey },
		CocPumShortcut                                                             { Grey },
		CocPumVirtualText                                                          { Grey },
		CocDisabled                                                                { Grey },
		CocFloatDividingLine                                                       { Grey },
		CocCodeLens                                                                { Grey },
		CocFadeOut                                                                 { Grey },
		CocStrikeThrough                                                           { Grey },
		CocListsDesc                                                               { Grey },
		ClapBlinesLineNr                                                           { Grey },
		EasyMotionShade                                                            { Grey },
		Blamer                                                                     { Grey },
		agitTree                                                                   { Grey },
		FloatermBorder                                                             { Grey },
		CmpItemAbbrDeprecated                                                      { Grey },
		NavicSeparator                                                             { Grey },
		TroubleSource                                                              { Grey },
		TroubleCode                                                                { Grey },
		TelescopeBorder                                                            { Grey },
		FzfLuaBorder                                                               { Grey },
		SnacksDashboardDir                                                         { Grey },
		SnacksPickerBorder                                                         { Grey },
		SnacksPickerTotals                                                         { Grey },
		HopUnmatched                                                               { Grey },
		NotifyDEBUGBorder                                                          { Grey },
		NotifyDEBUGIcon                                                            { Grey },
		NotifyDEBUGTitle                                                           { Grey },
		ReferencesCount                                                            { Grey },
		DefinitionCount                                                            { Grey },
		TargetFileName                                                             { Grey },
		MiniIndentscopeSymbol                                                      { Grey },
		MiniStarterItemBullet                                                      { Grey },
		LightspeedGreyWash                                                         { Grey },
		diffLine                                                                   { Grey },
		RainbowLevel1                                                              { Orange },
		WhichKeyGroup                                                              { Orange },
		agitRef                                                                    { Orange },
		agitStatMessage                                                            { Orange },
		CmpItemKindConstant                                                        { Orange },
		CmpItemKindProperty                                                        { Orange },
		CmpItemKindVariable                                                        { Orange },
		BlinkCmpKindConstant                                                       { Orange },
		BlinkCmpKindProperty                                                       { Orange },
		BlinkCmpKindVariable                                                       { Orange },
		NavicIconsConstant                                                         { Orange },
		NavicIconsProperty                                                         { Orange },
		NavicIconsVariable                                                         { Orange },
		RainbowDelimiterOrange                                                     { Orange },
		LspSagaDiagnosticSource                                                    { Orange },
		LspSagaDiagnosticBorder                                                    { Orange },
		diffNewFile                                                                { Orange },
		GitGutterChangeLineNr                                                      { Blue },
		Lf_hl_popup_prompt                                                         { Blue },
		CtrlPPrtCursor                                                             { Blue },
		RainbowLevel4                                                              { Blue },
		RainbowLevel8                                                              { Blue },
		WhichKeyDesc                                                               { Blue },
		agitHead                                                                   { Blue },
		agitTag                                                                    { Blue },
		agitStatFile                                                               { Blue },
		agitDiffHeader                                                             { Blue },
		CmpItemKind                                                                { Blue },
		CmpItemKindClass                                                           { Blue },
		CmpItemKindEnum                                                            { Blue },
		CmpItemKindInterface                                                       { Blue },
		CmpItemKindModule                                                          { Blue },
		CmpItemKindStruct                                                          { Blue },
		CmpItemKindTypeParameter                                                   { Blue },
		BlinkCmpKindClass                                                          { Blue },
		BlinkCmpKindEnum                                                           { Blue },
		BlinkCmpKindInterface                                                      { Blue },
		BlinkCmpKindModule                                                         { Blue },
		BlinkCmpKindStruct                                                         { Blue },
		BlinkCmpKindTypeParameter                                                  { Blue },
		NavicIconsClass                                                            { Blue },
		NavicIconsEnum                                                             { Blue },
		NavicIconsInterface                                                        { Blue },
		NavicIconsModule                                                           { Blue },
		NavicIconsStruct                                                           { Blue },
		NavicIconsTypeParameter                                                    { Blue },
		TelescopePromptPrefix                                                      { Blue },
		SnacksDashboardFile                                                        { Blue },
		SnacksDashboardHeader                                                      { Blue },
		SnacksDashboardIcon                                                        { Blue },
		SnacksPickerSelected                                                       { Blue },
		SnacksPickerBufFlags                                                       { Blue },
		HopNextKey2                                                                { Blue },
		RainbowDelimiterCyan                                                       { Blue },
		RainbowDelimiterBlue                                                       { Blue },
		DapUIScope                                                                 { Blue },
		DapUIDecoration                                                            { Blue },
		DapUIStoppedThread                                                         { Blue },
		DapUILineNumber                                                            { Blue },
		DapUIFloatBorder                                                           { Blue },
		DapUIBreakpointsPath                                                       { Blue },
		LspSagaDiagnosticInfo                                                      { Blue },
		LspSagaRenameBorder                                                        { Blue },
		LspSagaCodeActionBorder                                                    { Blue },
		LspSagaCodeActionTruncateLine                                              { Blue },
		LspSagaAutoPreview                                                         { Blue },
		MiniStarterQuery                                                           { Blue },
		Lf_hl_popup_spin                                                           { Purple },
		GitGutterChangeDeleteLineNr                                                { Purple },
		RainbowLevel5                                                              { Purple },
		CmpItemKindEnumMember                                                      { Purple },
		CmpItemKindUnit                                                            { Purple },
		CmpItemKindValue                                                           { Purple },
		BlinkCmpKindEnumMember                                                     { Purple },
		BlinkCmpKindUnit                                                           { Purple },
		BlinkCmpKindValue                                                          { Purple },
		NavicIconsEnumMember                                                       { Purple },
		NavicIconsUnit                                                             { Purple },
		NavicIconsValue                                                            { Purple },
		RainbowDelimiterViolet                                                     { Purple },
		NotifyTRACEBorder                                                          { Purple },
		NotifyTRACEIcon                                                            { Purple },
		NotifyTRACETitle                                                           { Purple },
		DapUIType                                                                  { Purple },
		DapUISource                                                                { Purple },
		LspSagaDefPreviewBorder                                                    { Purple },
		DefinitionIcon                                                             { Purple },
		MiniStarterHeader                                                          { Purple },
		LightspeedMaskedChar                                                       { Purple },
		diffFile                                                                   { Purple },
		diffIndexLine                                                              { Purple },
		SnacksDashboardTitle                                                       { RedItalic },
		CocGitChangeRemovedSign                                                    { PurpleSign },
		GitGutterChangeDelete                                                      { PurpleSign },
		SignifySignChangeDelete                                                    { PurpleSign },
		SignatureMarkerText                                                        { PurpleSign },
		CocErrorHighlight                                                          { ErrorText },
		LspErrorHighlight                                                          { ErrorText },
		LspDiagInlineError                                                         { ErrorText },
		YcmErrorSection                                                            { ErrorText },
		ALEError                                                                   { ErrorText },
		NeomakeError                                                               { ErrorText },
		SyntasticError                                                             { ErrorText },
		CocWarningHighlight                                                        { WarningText },
		LspWarningHighlight                                                        { WarningText },
		LspDiagInlineWarning                                                       { WarningText },
		YcmWarningSection                                                          { WarningText },
		ALEWarning                                                                 { WarningText },
		NeomakeWarning                                                             { WarningText },
		SyntasticWarning                                                           { WarningText },
		CocInfoHighlight                                                           { InfoText },
		LspInformationHighlight                                                    { InfoText },
		LspDiagInlineInfo                                                          { InfoText },
		ALEInfo                                                                    { InfoText },
		NeomakeInfo                                                                { InfoText },
		CocHintHighlight                                                           { HintText },
		LspHintHighlight                                                           { HintText },
		LspDiagInlineHint                                                          { HintText },
		NeomakeMessage                                                             { HintText },
		sym"@comment.note"                                                         { TSNote },
		sym"@markup.note"                                                          { TSNote },
		sym"@text.note"                                                            { TSNote },
		sym"@comment.warning"                                                      { TSWarning },
		sym"@text.warning"                                                         { TSWarning },
		sym"@comment.error"                                                        { TSDanger },
		sym"@text.danger"                                                          { TSDanger },
		CocHoverRange                                                              { gui="bold,underline", },
		CocSearch                                                                  { fg=palette.green, gui="bold", },
		CocPumSearch                                                               { fg=palette.green, gui="bold", },
		CocMarkdownHeader                                                          { fg=palette.blue, gui="bold", },
		CocMarkdownLink                                                            { fg=palette.green, gui="underline", },
		Lf_hl_match                                                                { fg=palette.green, gui="bold", },
		Lf_hl_match0                                                               { fg=palette.green, gui="bold", },
		Lf_hl_match1                                                               { fg=palette.blue, gui="bold", },
		Lf_hl_match2                                                               { fg=palette.red, gui="bold", },
		Lf_hl_match3                                                               { fg=palette.yellow, gui="bold", },
		Lf_hl_match4                                                               { fg=palette.purple, gui="bold", },
		Lf_hl_matchRefine                                                          { fg=palette.yellow, gui="bold", },
		Lf_hl_popup_normalMode                                                     { fg=palette.bg0, bg=palette.blue, gui="bold", },
		Lf_hl_popup_inputMode                                                      { fg=palette.bg0, bg=palette.green, gui="bold", },
		Lf_hl_popup_category                                                       { fg=palette.fg, bg=palette.bg4, },
		Lf_hl_popup_nameOnlyMode                                                   { fg=palette.fg, bg=palette.bg3, },
		Lf_hl_popup_fullPathMode                                                   { fg=palette.fg, bg=palette.bg3, },
		Lf_hl_popup_fuzzyMode                                                      { fg=palette.fg, bg=palette.bg3, },
		Lf_hl_popup_regexMode                                                      { fg=palette.fg, bg=palette.bg3, },
		Lf_hl_popup_lineInfo                                                       { fg=palette.bg0, bg=palette.blue, },
		Lf_hl_popup_total                                                          { fg=palette.bg0, bg=palette.red, },
		Lf_hl_popup_cursor                                                         { fg=palette.bg0, bg=palette.blue, },
		ClapSelected                                                               { fg=palette.red, gui="bold", },
		ClapCurrentSelection                                                       { bg=palette.bg0, gui="bold", },
		ClapSpinner                                                                { fg=palette.blue, bg=palette.bg2, gui="bold", },
		ClapBlines                                                                 { fg=palette.fg, },
		ClapProviderColon                                                          { ClapBlines },
		ClapProviderAbout                                                          { ClapBlines },
		ClapProviderId                                                             { fg=palette.fg, gui="bold", },
		ClapMatches1                                                               { fg=palette.red, gui="bold", },
		ClapMatches2                                                               { fg=palette.orange, gui="bold", },
		ClapMatches3                                                               { fg=palette.yellow, gui="bold", },
		ClapMatches4                                                               { fg=palette.blue, gui="bold", },
		ClapMatches5                                                               { fg=palette.purple, gui="bold", },
		ClapFuzzyMatches                                                           { fg=palette.green, gui="bold", },
		ClapFuzzyMatches1                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches2                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches3                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches4                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches5                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches6                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches7                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches8                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches9                                                          { ClapFuzzyMatches },
		ClapFuzzyMatches10                                                         { ClapFuzzyMatches },
		ClapFuzzyMatches11                                                         { ClapFuzzyMatches },
		ClapFuzzyMatches12                                                         { ClapFuzzyMatches },
		ClapSearchText                                                             { ClapFuzzyMatches },
		ClapNoMatchesFound                                                         { fg=palette.red, gui="bold", },
		deniteMatchedChar                                                          { fg=palette.green, gui="bold", },
		deniteMatchedRange                                                         { fg=palette.green, gui="bold,underline", },
		deniteInput                                                                { fg=palette.green, bg=palette.bg1, gui="bold", },
		deniteStatusLineNumber                                                     { fg=palette.purple, bg=palette.bg1, },
		deniteStatusLinePath                                                       { fg=palette.fg, bg=palette.bg1, },
		CtrlPMatch                                                                 { fg=palette.green, gui="bold", },
		CtrlPPrtBase                                                               { fg=palette.grey, },
		CtrlPLinePre                                                               { fg=palette.grey, },
		CtrlPMode1                                                                 { fg=palette.blue, bg=palette.bg1, gui="bold", },
		CtrlPMode2                                                                 { fg=palette.bg1, bg=palette.blue, gui="bold", },
		CtrlPStats                                                                 { fg=palette.grey, bg=palette.bg1, gui="bold", },
		MatchParenCur                                                              { gui="bold", },
		MatchWord                                                                  { gui="underline", },
		MatchWordCur                                                               { gui="underline", },
		SneakLabelMask                                                             { fg=palette.bg_green, bg=palette.bg_green, },
		VMCursor                                                                   { fg=palette.blue, bg=palette.grey_dim, },
		QuickScopePrimary                                                          { fg=palette.green, gui="underline", },
		QuickScopeSecondary                                                        { fg=palette.blue, gui="underline", },
		CmpItemAbbrMatch                                                           { fg=palette.green, gui="bold", },
		CmpItemAbbrMatchFuzzy                                                      { fg=palette.green, gui="bold", },
		BlinkCmpLabelMatch                                                         { fg=palette.green, gui="bold", },
		TelescopeMatching                                                          { fg=palette.green, gui="bold", },
		SnacksPickerMatch                                                          { fg=palette.green, gui="bold", },
		HopNextKey                                                                 { fg=palette.red, gui="bold", },
		HopNextKey1                                                                { fg=palette.blue, gui="bold", },
		IblScope                                                                   { fg=palette.grey, gui="nocombine", },
		IndentBlanklineContextChar                                                 { IblScope },
		IblIndent                                                                  { fg=palette.bg4, gui="nocombine", },
		IndentBlanklineChar                                                        { IblIndent },
		NotifyBackground                                                           { bg=palette.bg0, },
		DapUIModifiedValue                                                         { fg=palette.blue, gui="bold", },
		DapUIBreakpointsCurrentLine                                                { fg=palette.blue, gui="bold", },
		LspFloatWinBorder                                                          { fg=palette.bg0, bg=palette.bg0, },
		LspSagaDiagnosticHeader                                                    { fg=palette.orange, gui="bold", },
		LspSagaCodeActionTitle                                                     { fg=palette.blue, gui="bold", },
		DefinitionPreviewTitle                                                     { fg=palette.purple, gui="bold", },
		InclineNormalNC                                                            { fg=palette.grey, bg=palette.bg2, },
		MiniAnimateCursor                                                          { gui="reverse,nocombine", },
		MiniFilesFile                                                              { fg=palette.fg, },
		MiniFilesTitleFocused                                                      { fg=palette.green, bg=palette.bg2, gui="bold", },
		MiniHipatternsFixme                                                        { fg=palette.bg0, bg=palette.red, gui="bold", },
		MiniHipatternsHack                                                         { fg=palette.bg0, bg=palette.yellow, gui="bold", },
		MiniHipatternsNote                                                         { fg=palette.bg0, bg=palette.blue, gui="bold", },
		MiniHipatternsTodo                                                         { fg=palette.bg0, bg=palette.green, gui="bold", },
		MiniIconsAzure                                                             { fg=palette.bg_blue, },
		WhichKeyIconAzure                                                          { MiniIconsAzure },
		MiniIconsBlue                                                              { fg=palette.blue, },
		WhichKeyIconBlue                                                           { MiniIconsBlue },
		MiniIconsCyan                                                              { fg=palette.blue, },
		WhichKeyIconCyan                                                           { MiniIconsCyan },
		MiniIconsGreen                                                             { fg=palette.green, },
		WhichKeyIconGreen                                                          { MiniIconsGreen },
		MiniIconsGrey                                                              { fg=palette.fg, },
		WhichKeyIconGrey                                                           { MiniIconsGrey },
		MiniIconsOrange                                                            { fg=palette.orange, },
		WhichKeyIconOrange                                                         { MiniIconsOrange },
		MiniIconsPurple                                                            { fg=palette.purple, },
		WhichKeyIconPurple                                                         { MiniIconsPurple },
		MiniIconsRed                                                               { fg=palette.red, },
		WhichKeyIconRed                                                            { MiniIconsRed },
		MiniIconsYellow                                                            { fg=palette.yellow, },
		WhichKeyIconYellow                                                         { MiniIconsYellow },
		MiniIndentscopePrefix                                                      { gui="nocombine", },
		MiniJump2dSpot                                                             { fg=palette.red, gui="bold,nocombine", },
		MiniJump2dSpotAhead                                                        { fg=palette.blue, gui="nocombine", },
		MiniJump2dSpotUnique                                                       { fg=palette.yellow, gui="bold,nocombine", },
		MiniPickPrompt                                                             { fg=palette.blue, bg=palette.bg2, },
		MiniStarterCurrent                                                         { gui="nocombine", },
		MiniStatuslineDevinfo                                                      { fg=palette.fg, bg=palette.bg3, },
		MiniStatuslineFileinfo                                                     { fg=palette.fg, bg=palette.bg3, },
		MiniStatuslineFilename                                                     { fg=palette.grey, bg=palette.bg1, },
		MiniStatuslineInactive                                                     { fg=palette.grey, bg=palette.bg1, },
		MiniStatuslineModeCommand                                                  { fg=palette.bg0, bg=palette.yellow, gui="bold", },
		MiniStatuslineModeInsert                                                   { fg=palette.bg0, bg=palette.bg_green, gui="bold", },
		MiniStatuslineModeNormal                                                   { fg=palette.bg0, bg=palette.bg_blue, gui="bold", },
		MiniStatuslineModeOther                                                    { fg=palette.bg0, bg=palette.purple, gui="bold", },
		MiniStatuslineModeReplace                                                  { fg=palette.bg0, bg=palette.orange, gui="bold", },
		MiniStatuslineModeVisual                                                   { fg=palette.bg0, bg=palette.bg_red, gui="bold", },
		MiniTablineCurrent                                                         { fg=palette.fg, bg=palette.bg4, },
		MiniTablineHidden                                                          { fg=palette.grey, bg=palette.bg2, },
		MiniTablineModifiedCurrent                                                 { fg=palette.blue, bg=palette.bg4, },
		MiniTablineModifiedHidden                                                  { fg=palette.grey, bg=palette.bg2, },
		MiniTablineModifiedVisible                                                 { fg=palette.blue, bg=palette.bg2, },
		MiniTablineTabpagesection                                                  { fg=palette.bg0, bg=palette.blue, gui="bold", },
		MiniTablineVisible                                                         { fg=palette.fg, bg=palette.bg2, },
		MiniTestEmphasis                                                           { gui="bold", },
		MiniTestFail                                                               { fg=palette.red, gui="bold", },
		MiniTestPass                                                               { fg=palette.green, gui="bold", },
		MiniTrailspace                                                             { bg=palette.red, },
		LightspeedLabel                                                            { fg=palette.red, gui="bold,underline", },
		LightspeedLabelDistant                                                     { fg=palette.blue, gui="bold,underline", },
		LightspeedShortcut                                                         { fg=palette.bg0, bg=palette.red, gui="bold", },
		LightspeedUnlabeledMatch                                                   { fg=palette.fg, gui="bold", },
		LightspeedPendingOpArea                                                    { fg=palette.bg0, bg=palette.green, },
		-- }}}
	}
end)

return theme
