#!/usr/bin/env ruby

require 'fileutils'
include FileUtils

begin
  require 'highline/import'
rescue LoadError
  STDERR.puts 'Installing highline.'
  system 'gem', 'install', 'highline'
  exec $0, *ARGV
end

def run(*args)
  system *args
  exit $?.exitstatus if $?.exitstatus > 0
end

if ARGV.length == 0
  exec ENV['BROWSER'], 'https://aur4.archlinux.org/packages'
end

package = ARGV[0]
if File.directory? package
  puts ":: Deleting old version of #{package}."
  rm_rf package
end
puts ':: Fetching updated version.'
run 'get', '-z', "https://aur.archlinux.org/cgit/aur.git/snapshot/#{package}.tar.gz"

Dir.chdir package do
  puts ':: Making package.'
  run 'makepkg'

  install = ask(":: Install #{package}? [Y/n] ") { |s| s.in = ['', 'y', 'n']}
  if install != 'n'
    run 'sudo', 'pacman', '-U', '--noconfirm', *Dir['*.pkg.tar.xz']
  end

  puts ':: Cleaning package folder'
  rm_rf 'pkg' if File.exist? 'pkg'
  rm_rf 'src' if File.exist? 'src'
end

puts ':: Stashing packages in pkg/.'
mv Dir["#{package}/*.pkg.tar.xz"], 'pkg/'
