#!/usr/bin/env zsh

i=0
until "$@" ; do
  delay=$(( int(1.5 ** $i) ))
  echo "==> [$(date)] Retrying after $delay minute..."
  sleep $(( $delay * 60 ))
  i=$(( $i + 1 ))
done
echo "==> Successfully ran $*"
