#!/usr/bin/env zsh

local target=${1:-fg}

case $target in
  fg)
    local t=38
    ;;
  bg)
    local t=48
    ;;
  *)
    echo "Unsupported target: $1" 1>&2
    return 1
    ;;
esac

echo "16 colours:\n"

echo -n "Dim:    "
for i in `seq 0 7`; do
  v=$((30 + $i))
  echo -n "\e[2;${v}m ${(l:3:: :)i}"
done
echo "\e[0m "

echo -n "Normal: "
for i in `seq 0 7`; do
  v=$((30 + $i))
  echo -n "\e[${v}m ${(l:3:: :)i}"
done
for i in `seq 0 7`; do
  v=$((40 + $i))
  echo -n "\e[;${v}m ${(l:3:: :)i}"
done
echo "\e[0m "

echo -n "Bold:   "
for i in `seq 0 7`; do
  v=$((30 + $i))
  echo -n "\e[1;${v}m ${(l:3:: :)i}"
done
echo "\e[0m "; echo

echo "\n256 colours:\n"

for i in `seq 0 15`; do
  echo -n "\e[${t};5;${i}m ${(l:3:: :)i}"
done
echo "\e[0m "; echo

for h in `seq 0 1`; do
  for i in `seq 0 5`; do
    for j in `seq 0 2`; do
      for k in `seq 0 5`; do
        v=$((16 + $h * 108 + $i * 6 + $j * 36 + $k))
        echo -n "\e[${t};5;${v}m ${(l:3:: :)v}"
      done
      echo -n "  "
    done
    echo "\e[0m"
  done
  echo
done

for j in `seq 0 3`; do
  for k in `seq 0 5`; do
    v=$((232 + $j * 6 + $k))
    echo -n "\e[${t};5;${v}m ${(l:3:: :)v}"
  done
  echo " \e[0m"
done
echo $terminfo[sgr0]
