#!/bin/zsh

local MX
local yellow=$terminfo[bold]$fg[yellow]
local reset=$terminfo[sgr0]

echo "$yellow  Domain info for ${1:?You must specify a domain to get information for.}$reset"
echo "$yellow  Nameservers:$reset"
dig +short -t NS $1
echo "$yellow  MX:$reset"
MX=`dig +short -t MX $1 | sort -k 1 -n`
echo $MX
echo "$yellow  A:$reset"
for name in `echo $MX | awk "{ print \\\$2 }"`; do
  echo "$name: `dig +short -t A $name`"
done
echo "$1: `dig +short -t A $1`"
echo "www.$1: `dig +short -t A www.$1`"

