#!/bin/zsh

local IFS=$'\n'
for branch in $(git branch -r --merged master | grep -v master | sed -E 's!^  ([^/]+)/!\1 --delete !'); do
  IFS=' '
  read -rA broken <<<"$branch"
  git push --no-verify $broken
  IFS=$'\n'
done
git branch -r --merged master | grep -v master | sed 's!  remotes/!!' | xargs git branch -dr
