#!/bin/zsh

# Ensure our idea of what the remotes are is accurate
git fetch --all --prune

# Blow away everything that's on a remote and merged into master
local IFS=$'\n'
for branch in $(git branch -r --merged master | grep -v master | sed -E 's!^  ([^/]+)/!\1 --delete !'); do
  IFS=' '
  read -rA broken <<<"$branch"
  git push --no-verify $broken
  IFS=$'\n'
done
