#!/bin/zsh

local bare_prompt=${(%):-(${PR_USER})- }

unset PR_RUBY
if [[ -n "$rvm_version" ]]; then
  local rvm_color="$PR_GREEN"
  local rvm_version=`rvm current`
  if [[ "$rvm_version" == "system" ]]; then
    rvm_color="${PR_RED}"
  fi
  bare_prompt="${bare_prompt}-[${rvm_version}]"
  PR_RUBY="${PR_LIGHT_BLACK}${PR_SHIFT_IN}${PR_HBAR}${PR_SHIFT_OUT}[${rvm_color}${rvm_version}${PR_LIGHT_BLACK}]${PR_NO_COLOR}"
fi

PR_GIT=`parse_git_branch`
if [[ -n "$PR_GIT" ]]; then
  bare_prompt="${bare_prompt}-[${PR_GIT}]"
  PR_GIT="${PR_LIGHT_BLACK}${PR_SHIFT_IN}${PR_HBAR}${PR_SHIFT_OUT}[${PR_GREEN}${PR_GIT}${PR_LIGHT_BLACK}]${PR_NO_COLOR}"
fi

PR_EMAIL=''
mail -e &> /dev/null
if [[ $? -eq 0 ]]; then
  bare_prompt="${bare_prompt}-[*]"
  PR_EMAIL="${PR_LIGHT_BLACK}${PR_SHIFT_IN}${PR_HBAR}${PR_SHIFT_OUT}[${PR_LIGHT_YELLOW}E${PR_LIGHT_BLACK}]${PR_NO_COLOR}"
fi

local TERMWIDTH
(( TERMWIDTH = ${COLUMNS} - 1 ))
local promptsize=${#${bare_prompt}}
PR_FILLBAR="\${(l.(($TERMWIDTH - $promptsize))..${PR_HBAR}.)}"

if [[ "$USER" == "root" ]]; then
  PR_USER_COLOR="${PR_RED}"
fi
