#!/usr/bin/env zsh

# Our general exit handler. Borrowed from https://unix.stackexchange.com/a/322213
cleanup() {
  err=$?

  # Do your actual cleanup here.
  ssh $SSH_JUMPBOX "rm -r $TMPFILE" &> /dev/null

  trap '' EXIT INT TERM
  return $err
}
sig_cleanup() {
  trap '' EXIT # some shells will call EXIT after the INT handler
  false # sets $?
  cleanup
}
trap cleanup EXIT
trap sig_cleanup INT QUIT TERM

local TMPFILE="/tmp/ssh-config-$(date '+%Y%m%d%M%s')"
local DISALLOWED_VARIABLES='^(ciphers|macs|.*algorithms|.*keytypes|identityfile) |^global'

ssh -G "$@" | egrep -v "$DISALLOWED_VARIABLES" | ssh $SSH_JUMPBOX "touch $TMPFILE; chmod 0600 $TMPFILE; cat > $TMPFILE" &> /dev/null
ssh -tA $SSH_JUMPBOX "ssh -F $TMPFILE $@"
